### ISSUE TITLE
Error installing Harmony

### ISSUE THREAD

**Issue by HugoGonzalezVelozo** [immunogenomics/harmony#10]
Hi, I tried to install harmony to re-analyze my single cells data, but during the installation I get an error (see below),  what can I do?

Thanks 
Hugo

#script
library(devtools)
install_github("immunogenomics/harmony")

#error during installation
harmony.cpp:236:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o harmony.so RcppExports.o harmony.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [harmony.so] Error 1
ERROR: compilation failed for package ‘harmony’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/harmony’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/b2/hbzb_1z55m3blt741k_qkl_00000gn/T//RtmpS7JdBJ/file72c6228a00f/harmony_0.1.0.tar.gz’ had non-zero exit status

**Comment by ilyakorsunsky** [comment]
Hugo, from *d: library not found for -lgfortran*, it seems like you don't have the fortran libraries on your library path. Can you make sure that it is installed and on your path?

**Comment by aemoor** [comment]
I had the same compilation error  (MacOS, Fortran installed with Homebrew). I found this solution online, afterwards the installation worked.

Create a Makevars file in the folder ~/.R
add this line Makevars:
````
FLIBS=`gfortran -print-search-dirs | grep '^libraries:' | sed 's|libraries: =||$
```

**Comment by ilyakorsunsky** [comment]
Hi @aemoor, @HugoGonzalezVelozo,

Is this still an issue for either of you? If not, I will close the thread. 

Cheers, 
Ilya

**Comment by ankushs0128** [comment]
> I had the same compilation error (MacOS, Fortran installed with Homebrew). I found this solution online, afterwards the installation worked.
> 
> Create a Makevars file in the folder ~/.R (if you don't have one already), then add this line to the Makevars file:
> 
> ```
> FLIBS=`gfortran -print-search-dirs | grep ^libraries: | sed 's|libraries: =||' | sed 's|:| -L|g' | sed 's|^|-L|'`
> ```

with  R version 4, I´m still having the same problem installing Harmony

My  makevars file looks likes this

`FC = /usr/local/gfortran/bin/gfortran
FLIBS=`gfortran -print-search-dirs | grep ^libraries: | sed 's|libraries: =||' | sed 's|:| -L|g' | sed 's|^|-L|'`
CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function`

**Comment by lyuguol** [comment]
> Hi, I tried to install harmony to re-analyze my single cells data, but during the installation I get an error (see below), what can I do?
> 
> Thanks
> Hugo
> 
> #script
> library(devtools)
> install_github("immunogenomics/harmony")
> 
> #error during installation
> harmony.cpp:236:1: warning: control may reach end of non-void function [-Wreturn-type]
> }
> ^
> 1 warning generated.
> clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o harmony.so RcppExports.o harmony.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
> ld: library not found for -lgfortran
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [harmony.so] Error 1
> ERROR: compilation failed for package ‘harmony’
> 
> * removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/harmony’
>   Error in i.p(...) :
>   (converted from warning) installation of package ‘/var/folders/b2/hbzb_1z55m3blt741k_qkl_00000gn/T//RtmpS7JdBJ/file72c6228a00f/harmony_0.1.0.tar.gz’ had non-zero exit status

Hello Hugo, 

Have you managed to install the package on your Mac? I encountered a similar problem..

I look forward to your reply.


Many thanks in advance.

Guoliang
