### ISSUE TITLE
Recommendation on multi-study, multi-sample integration

### ISSUE THREAD

**Issue by zji90** [immunogenomics/harmony#100]
Hi,
I would like to seed some advice on how to use harmony to integrate scRNA-seq data from multiple studies, and each study contains information about multiple samples.
There are two possibilities I have tried, one is to ignore the study information and simply run 'RunHarmony(data, 'sample')' where sample here indicates all different samples from all the studies (regardless of which study each sample comes from). Another is to keep the study information and run 'RunHarmony(data, 'study','sample')', where sample again indicates the different samples but study indicates different studies.
I wonder which of the two makes more sense. Thanks!

**Comment by ilyakorsunsky** [comment]
Dear @zji90, 

I would always suggest integrating over two variables, as this more accurately represents the source of confounding effects in your study. While you could get similar integrated embedding with both approaches, you should be able to achieve integration with smaller theta values with both variables. For instance, you may need theta=2 for 'sample' only but you could use theta=c(0.5, 0.5) for 'sample' and 'study', for instance. 

Best, 
Ilya
