### ISSUE TITLE
How to avoid over-correction in using harmony?

### ISSUE THREAD

**Issue by Lukadon77** [immunogenomics/harmony#101]
Hey, I have tried harmony for batch effect correction for my single-cell RNA-seq data to compare the differeces between tumor and normal tissues, but I found one problem is that when I tried to integrate all the samples with harmony, the results showed an over-correction between tumor and normal tissues, e.g. exhausted T cells, which were only present in tumors, could be found on normal tissues after harmony correction. How can I solve this problem? Can I solved this problem by modifying some of the parameters in RUNHarmony function? or any function else?

**Comment by ilyakorsunsky** [comment]
Dear @Lukadon77, 

This is a very important question that blurs the lines between a technical issue and a biological one. From the technical side, you could try to adjust parameters, such as decreasing theta and increasing lambda, to achieve a less integrated embedding. From the biological side, I would ask why Harmony is merging these T cells between tumor and normal tissue. That is, if you do differential gene expression to find markers for these exhausted T cells in tumor and harmonized T cells in normal tissue, is there some set of genes that is driving their similarity? 

Hope this helps! 

Best, 
Ilya
