### ISSUE TITLE
getting harmony corrected count matrix

### ISSUE THREAD

**Issue by amjass12** [immunogenomics/harmony#102]
Hi, 

Is there a way of extracting harmony corrected counts from a seurat object. While harmony used nearest neighbours, is there any internal restructuring of batch corrected counts that can be extracted / used for other downstream analyses?

thanks

**Comment by jmrussell** [comment]
Can we take the harmony embeddings and loadings from the Seurat object and multiply the matrices together, and then scale the data by column (which would be by cell)?

**Comment by pfgherardini** [comment]
I am also interested in knowing whether there is a way to do this. Any ideas?

**Comment by pati-ni** [comment]
Please see #182 

> Harmony is designed to correct cell embeddings. Therefore, it is not possible to correct the gene expression matrix. While you can provide scaled gene values, it is not guaranteed to provide best results.
> 
> Hope this addresses the question.
