### ISSUE TITLE
Harmony after subsetting data

### ISSUE THREAD

**Issue by jennapappalardo** [immunogenomics/harmony#104]
Hello-
I've been using Harmony to integrate single cell data and I was wondering what your recommendations are for re-running Harmony after subsetting data (for example, wanting to extract a cluster and re-cluster it). While it might not be necessary from an integration perspective, I'm interested in doing that to ensure the PCs I'm using are reflective of the subsetted population rather than the total dataset for sub-clustering.

Thanks!

**Comment by ilyakorsunsky** [comment]
Dear @jennapappalardo, 

I do recommend re-running all steps from scaling (or normalizing if using SC-transform) through Harmony after subsetting. Doing this will give you more resolution in your more focused dataset. 

Best, 
Ilya
