### ISSUE TITLE
format for normalized gene expression matrix and its meta_data

### ISSUE THREAD

**Issue by xs-sean** [immunogenomics/harmony#107]
hi there ~~
I am trying to use harmony to correct batch effect of transcriptomes from different projects.
Per your introduction, 
"By default, Harmony inputs a normalized gene expression matrix
harmony_embeddings <- HarmonyMatrix(exprs_matrix, meta_data, 'dataset')"

So I have tried this function in my datasets, however, there is always an error massage says:
"Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
  BLAS/LAPACK routine 'DLASCLS' gave error code -4
In addition: Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion
"
I have no idea where this error from and guess that this might because of the format of my expression matrix and meta_data?

Thanks in advance for your help!
Regards,
Shixue
University of Macau

**Comment by ilyakorsunsky** [comment]
Dear @xs-sean, 

Based on the error message, your suspicion is very reasonable. In case this helps, the format of the expression matrix is a dgCMatrix (from the R Matrix package) with genes in rows and cells in columns. The meta_data table should be a data.frame object of cells by features. 

Best, 
Ilya
