### ISSUE TITLE
Harmony converged after 3 iterations

### ISSUE THREAD

**Issue by peixiaoya** [immunogenomics/harmony#108]
My aim is integrate 7 samples  scRNA-seq data.

I use harmony as follow commands:

#First I merge 7 samples  data into 1 dataset
mymerg<-merge(x=sceList[[7]],y=c(sceList[[1]],sceList[[2]],sceList[[3]],sceList[[4]],sceList[[5]],sceList[[6]]))

#Then do the next steps: 
mymerg <- NormalizeData(mymerg, normalization.method = "LogNormalize", scale.factor = 10000)
mymerg <- FindVariableFeatures(mymerg, selection.method = "vst", nfeatures = 2000)
mymerg <- ScaleData(mymerg,features=VariableFeatures(mymerg)) 
mymerg <- RunPCA(mymerg, features = VariableFeatures(object = mymerg))
mymerg <- FindNeighbors(mymerg, dims = 1:20)
mymerg <- FindClusters(mymerg, resolution = 0.2)

#The "orig.ident" grouped by different samples
mymerg <- RunHarmony(mymerg, "orig.ident")
mymerg <- RunUMAP(mymerg, reduction = "harmony")

But in these RunHarmony process, there have errors. 
#The error is:

Harmony 1/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 2/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 3/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony converged after 3 iterations
Warning: Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony; see ?make.names for more details on syntax validity
Warning messages:
1: did not converge in 25 iterations 
2: did not converge in 25 iterations 
Error in RunUMAP.Seurat(mymerg, reduction = "harmony") : 
  Please specify one of dims, features, or graph
Calls: RunUMAP -> RunUMAP.Seurat
Execution halted

I have no idea about why the Harmony process only done 30%.

**Comment by AmelZulji** [comment]
Hi @peixiaoya,

Hopefully this late response might be of some help for you.

For the first question:

> I have no idea about why the Harmony process only done 30%.

I assume you are referring to the harmony iterations (1/10, 2/10, 3/10) which shows how many iterations harmony performed out of maximal possible iterations specified by  `max.iter.harmony` argument, which is by default 10. So, its not that harmony performed only 30% of its job, it rather shows that it converged on 3rd iteration out of maximally 10. It is not an error.

I presume that this part was copied from another run:

> Warning messages:
> 1:  did not converge in 25 iterations
> 2: did not converge in 25 iterations

As for the specific error: 

> Error in RunUMAP.Seurat(mymerg, reduction = "harmony") :
> Please specify one of dims, features, or graph

you need to specify `dims` argument within the function `RunUMAP()`, something like: 

`mymerg <- RunUMAP(mymerg, reduction = "harmony", dims = 1:10)` please note that `dims = 1:10` means that for umap you are using first 10 PCs. You may want to adjust that number based on the `ElbowPlot()`.

Hope this helps.

Best,
Amel

**Comment by ilyakorsunsky** [comment]
Dear @AmelZulji, Thanks for posting a great answer to this!
