### ISSUE TITLE
Unable to use DESeq2 with Seurat 3.9.9.9002, R version 4.01

### ISSUE THREAD

**Issue by mskmanishar** [immunogenomics/harmony#109]
Hi,
 I want to perform differential expression analysis in Seurat for scRNA-seq data sets in R version4.01. Is there any package available for the new version of R (4.01).
Thank you

**Comment by ilyakorsunsky** [comment]
Hi mskmanishar, 

This sounds like an issue for Seurat and DESeq2 and may be independent of Harmony. 

Thanks, 
Ilya
