### ISSUE TITLE
Issue with N <- nrow(meta_data) = 0 in HarmonyMatrix function

### ISSUE THREAD

**Issue by catsargent** [immunogenomics/harmony#11]
Hi,
I am trying to use harmony within a jupyter notebook. For the meta_data variable, I have a python factor stored but when I run the following (substituted with my variable names):
HarmonyMatrix(pc_mat, meta_data, vars_use, theta=4)
I get an error saying:
`Error in if (ncol(pc_mat) != N) { : argument is of length zero`

The issue is that when `N <- nrow(meta_data)` is run in the function HarmonyMatrix, it returns 0. 

Could you confirm the format that is expected by the variable `meta_data`? Should it be a factor? If so, shouldn't the check in HarmonyMatrix be `N <- length(meta_data)`?

I hope this makes sense!
Thanks,
Catherine

**Comment by ilyakorsunsky** [comment]
Dear Catherine, 

In the recent release, I changed the format to accept a data.frame (or similar object) for meta_data. The idea is to be able to integrate over multiple variables defined in the meta_data table, e.g. donor and technology. For compatibility, I added support for passing a character or factor vector, like you did above. 

Let me know if you're still having problems! 

Ilya

**Comment by ilyakorsunsky** [comment]
Dear @catsargent, 

Please let me know if you're still having this issue. I'd love to help you solve it!

Best, 
Ilya
