### ISSUE TITLE
Speed up

### ISSUE THREAD

**Issue by zji90** [immunogenomics/harmony#110]
Hi,
We are running Harmony on a very large dataset integrating scRNA-seq from 400+ samples. It seems that it may take a few days for the algorithm to finish. I wonder whether there is any suggestion to speed up harmony on such large datasets?

Thanks!

**Comment by ilyakorsunsky** [comment]
Dear zji90, 

A few days sounds like a long time, even for such a large dataset. Would it be possible to share more about the exact data dimensions (genes, cells, PCs) and harmony parameters (do_pca, nclusters, theta, number of iterations)? 

Thanks for raising this issue! 

Best, 
Ilya

**Comment by bli25broad** [comment]
@zji90 , you can also try Harmony-PyTorch https://github.com/lilab-bcb/harmony-pytorch
