### ISSUE TITLE
Iteratively integrating new samples to reference vs. integrating all new samples to reference simultaneously

### ISSUE THREAD

**Issue by bdj34** [immunogenomics/harmony#112]
Hi and thank you for this tool, especially for adding the `reference_values` feature. 

Initially, I have PCA embeddings for a reference dataset and several additional samples. I would like to integrate the additional samples while keeping the reference PCA embeddings unchanged. The `reference_values` option is perfect for this, but I have a follow up question related to the inner workings of Harmony when `reference_values` is used. 

Essentially, does the presence of other query cells affect the integration? That is, if I integrate one sample with my reference (using `reference_values = referenceData`) will I get the same corrected embeddings for that sample as I would if I integrated two samples at the same time?

I don't have enough memory on my local machine to integrate all at once, so I was hoping I could do it sample by sample without affecting the integration process.

Thanks!

Brian

**Comment by ilyakorsunsky** [comment]
Hi Brian, 

This is a very timely question! We have developed a new algorithm called Symphony to do this sort of reference mapping efficiently. Please find more information at the Symphony github and the accompanying preprint. 

https://github.com/immunogenomics/symphony
https://www.biorxiv.org/content/10.1101/2020.11.18.389189v1

Best, 
Ilya

**Comment by bdj34** [comment]
Wow, that's great. Thank you!
