### ISSUE TITLE
function do_umap

### ISSUE THREAD

**Issue by evanpk** [immunogenomics/harmony#118]
Hello, I am trying to reproduce the figures from the 2019 manuscript and can't find the function "do_umap". Is there a package that this comes from? Thank you

**Comment by ilyakorsunsky** [comment]
Dear @evanpk, 

Unfortunately, this function is not part of the Harmony package. Please refer to the github for this manuscript (https://github.com/immunogenomics/harmony2019) to see these support functions. 

Best, 
Ilya
