### ISSUE TITLE
Typo in the Seurat vignette + Error while running RunHarmony

### ISSUE THREAD

**Issue by sumeetpalsingh** [immunogenomics/harmony#12]
Thanks for developing Harmony, and integrating it with Seurat. It is simple to use, and surely faster.

However, I had a few issues: 
Firstly, there was no documentation for the functions. ?RunHarmony did not return any help. This was a bit frustrating, as I could not understand the parameters.

Secondly, in the vignette 'Aligning 10X PBMCs' presented, I think the command,
> system.time(pbmc %<>% RunHarmony("stim", theta = 2, plot_convergence = TRUE, nclust = 50, 
>                                  max.iter.cluster = 100, max.iter.harmony = 4))
> 
should have max.iter.harmony = 10, as the run shows 10 iterations from 1/10 till the end. 
This was confusing to me as I did not understand this incongruity at first. Just a small thing to fix :)

Third and last, I actually did not get RunHarmony to run. I got the error:
Error in if (return_object) { : argument is not interpretable as logical

I couldn't understand why this was happening. The command would run iterations, converge, plot, and then give error. 

Thus, I went inside the code and ran all the commands following HarmonyMatrix individually. They all ran perfectly, and I could get harmony to work. I cannot point exactly to the reason why this error is occurring. 

One more thing, and this is only to clear a confusion I had: the 'dims.use' is not actually passed to HarmonyMatrix. Why is it calculated in RunHarmony command.

Sorry to combine multiple issues together. But once Harmony started working, the speed and results were impressive. Hopefully, these things can be sorted out!

**Comment by wyattmcdonnell** [comment]
Hi @ilyakorsunsky just wanted to let you know that I'm getting the exact same `Error in if (return_object) { : argument is not interpretable as logical` error on every Seurat object using the latest version of the `RunHarmony()` function. 

However, as @sumeetpalsingh has mentioned, running something like the following yields a beautiful convergence plot and embeddings that can be happily put back into the Seurat object:
```
#Store data for Harmony
pc_mat <- seurat@dr$pca@cell.embeddings
meta_data <- seurat@meta.data

#Run Harmony!
harmony_embeddings <- HarmonyMatrix(pc_mat = pc_mat, meta_data = meta_data, 
   vars_use = "orig.ident", plot_convergence = TRUE)

#Store new embeddings and make example plot
seurat <- SetDimReduction(seurat, reduction.type = 'harmony', slot = 'cell.embeddings', 
   new.data = harmony_embeddings)
seurat <- SetDimReduction(seurat, reduction.type = "harmony", slot = "key", 
   new.data = "Harmony")
seurat <- ProjectDim(seurat, reduction.type = "harmony", replace.dim = T, do.print = F)
DimPlot(seurat, reduction.use = 'harmony')
```
I hope this helps! Also, if you'd like somebody to write function documentation for `RunHarmony()`, let me know—I'd be happy to lend a hand. 

Best wishes,
Wyatt

**Comment by ShuyangZhao** [comment]
I'm getting the same error Error in if (return_object) { : argument is not interpretable as logical .
Is there a fix to this yet? or i have to manually run the HarmonyMatrix() function instead.

**Comment by ilyakorsunsky** [comment]
The bug turned out to be a new parameter I added to the interface. Please try it out now, it should work as expected again! 

@sumeetpalsingh note that I changed a few parameters for the vignette. With a recent (different) bug fix, we only need at most rounds 20 of clustering and 3 rounds of Harmony (~20sec total) to get the previous level of integration. Thanks @sumeetpalsingh @wyattmcdonnell @ShuyangZhao for your patience and comments! 

@wyattmcdonnell we were rightly asked to provide more detailed documentation for the manuscript revisions! More thorough documentation should be up on the github in a week or two - would love to get feedback from you

**Comment by shabs24** [comment]
Hi, 
I am still running into the same issue. I am working with Seurat object. I have tried to run the pbmc example in the vignette and getting the same error. Any suggestions ?

**Comment by ghoshal** [comment]
Hi @ilyakorsunsky ,

I am somehow still getting the same error. I reinstalled the package and reloaded it. Still getting this error 
Error in if (return_object) { : argument is not interpretable as logical

Please let me know what I should do.

**Comment by ilyakorsunsky** [comment]
Dear @ghoshal,

Are you still getting this error? I'd love to help if you are! 

Best, 
Ilya

**Comment by ilyakorsunsky** [comment]
@ghoshal Would you be able to send me a reproducible example? It would make it easier to debug

**Comment by ghoshal** [comment]
Hey @ilyakorsunsky ,

It started working. I closed down all Rstudio instances and restarted and it started working properly.

Thanks,

Bibaswan

**Comment by ilyakorsunsky** [comment]
Great to hear!

**Comment by sumeetpalsingh** [comment]
Thanks for the update! We are using Harmony for teaching integration in Single-cell RNA-Seq. course at our institute :)
