### ISSUE TITLE
installing harmony

### ISSUE THREAD

**Issue by gabrieljmarques** [immunogenomics/harmony#121]
Dear all, I'm trying to download your package, but it seems not to be working at my macOS

`devtools::install_github("immunogenomics/harmony")
`

> Downloading GitHub repo immunogenomics/harmony@HEAD
✓  checking for file ‘/private/var/folders/vq/61w19pmn3175c98rfmprwchh0000gn/T/RtmpmprJ5i/remotes193da534228/immunogenomics-harmony-c8f4901/DESCRIPTION’ ...
─  preparing ‘harmony’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘harmony_1.0.tar.gz’
   

> * installing *source* package ‘harmony’ ...

> ** using staged installation

> ** libs

> clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o

> In file included from RcppExports.cpp:4:

In file included from ./harmony_types.h:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo:21:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_check.hpp:50:4: error: "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
  #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
   ^
In file included from RcppExports.cpp:4:
In file included from ./harmony_types.h:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo:85:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:149:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:150:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:151:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:161:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:162:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:163:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = true;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:173:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:174:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = true;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:175:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:185:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = true;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:186:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:187:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:197:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = T1::is_row;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:198:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = T1::is_col;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:199:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = T1::is_xvec;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:209:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:210:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:211:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘harmony’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/harmony’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/harmony’
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/vq/61w19pmn3175c98rfmprwchh0000gn/T//RtmpmprJ5i/file193d601c5563/harmony_1.0.tar.gz’ had non-zero exit status

I tried to install it from zip, also did not work. Reinstalled rccp, did not help.

can u help pls?

see my sessioInfo():

> R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RcppAnnoy_0.0.18         RcppProgress_0.4.2       RcppHNSW_0.3.0           RcppEigen_0.3.3.9.1     
[5] RcppArmadillo_0.10.2.2.0 Rcpp_1.0.6              

loaded via a namespace (and not attached):
 [1] tinytex_0.30        xfun_0.22           remotes_2.2.0       purrr_0.3.4         lattice_0.20-41    
 [6] testthat_3.0.2      miniUI_0.1.1.1      usethis_2.0.1       htmltools_0.5.1.1   rlang_0.4.10       
[11] pkgbuild_1.2.0      later_1.1.0.1       glue_1.4.2          withr_2.4.1         RColorBrewer_1.1-2 
[16] sessioninfo_1.1.1   lifecycle_1.0.0     devtools_2.3.2      codetools_0.2-18    memoise_2.0.0      
[21] callr_3.5.1         fastmap_1.1.0       httpuv_1.5.5        ps_1.6.0            curl_4.3           
[26] xtable_1.8-4        promises_1.2.0.1    BiocManager_1.30.10 cachem_1.0.4        desc_1.3.0         
[31] pkgload_1.2.0       mime_0.10           fs_1.5.0            ggExtra_0.9         digest_0.6.27      
[36] processx_3.4.5      shiny_1.6.0         rprojroot_2.0.2     grid_4.0.4          cli_2.3.1          
[41] tools_4.0.4         magrittr_2.0.1      crayon_1.4.1        ellipsis_0.3.1      Matrix_1.3-2       
[46] prettyunits_1.1.1   assertthat_0.2.1    rstudioapi_0.13     R6_2.5.0            compiler_4.0.4

**Comment by dchiangboston** [comment]
I have encountered the same problem with the installation from Github, due to the incorrect C++ compiler being selected for the new Mac M1 chip.  The Bioconductor installation recommends reverting to R version 3.5, but the R version 3.5 binary package is no longer available for download.

**Comment by dchiangboston** [comment]
I was able to fix this problem by changing the R compiler settings for MacOS 10.15.17 running on M1 chip:

In the ~/.R/Makevars file:
CC=clang -std=c++11
CXX = clang++ -std=c++11

**Comment by ilyakorsunsky** [comment]
Dear @gabrieljmarques and @dchiangboston,

Harmony is also now available on CRAN! Does `install.packages("harmony")` let you install harmony? 

Best, 
Ilya
