### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by lvweiming** [immunogenomics/harmony#124]
The first error when installing harmony is sh: 1 /bin/gtar: not found.
This problem solved after I run the command as suggested by the Rstudio community. 
When I tried to install harmony again. The new error is missing value where TRUE/FALSE needed.
How can I resolve this problem?
Thank you in advance

**Comment by ilyakorsunsky** [comment]
Dear @lvweiming, 

Harmony is now available to install from CRAN! Can you try to use `install.packages("harmony")` and see if that works? 

Best, 
Ilya
