### ISSUE TITLE
Error In Installation 

### ISSUE THREAD

**Issue by ucsdhusky** [immunogenomics/harmony#128]
I encountered a problem in downloading harmony using: install_github("immunogenomics/harmony"). 
Here is what occurs when I run the above code:
Downloading GitHub repo immunogenomics/harmony@HEAD
✓  checking for file ‘/private/var/folders/ww/j0vvgswj76zb_km9fdpsdpw40000gn/T/RtmpHG4pkU/remotes824f24085d7/immunogenomics-harmony-c8f4901/DESCRIPTION’ ...
─  preparing ‘harmony’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘harmony_1.0.tar.gz’
   
Installing package into ‘/Users/xinyiwang/Library/R/4.0/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Users/xy/Library/R/4.0/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./harmony_types.h:1:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo:21:
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/compiler_check.hpp:50:4: error: "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
  #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
   ^
In file included from RcppExports.cpp:4:
In file included from ./harmony_types.h:1:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo:85:
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:149:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:150:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:151:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:161:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:162:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:163:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = true;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:173:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:174:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = true;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:175:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:185:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = true;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:186:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:187:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:197:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = T1::is_row;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:198:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = T1::is_col;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:199:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = T1::is_xvec;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:209:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:210:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:211:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘harmony’
* removing ‘/Users/xy/Library/R/4.0/library/harmony’
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/ww/j0vvgswj76zb_km9fdpsdpw40000gn/T//RtmpHG4pkU/file824f5a12e768/harmony_1.0.tar.gz’ had non-zero exit status
> 
> install_github("immunogenomics/harmony")
Downloading GitHub repo immunogenomics/harmony@HEAD
✓  checking for file ‘/private/var/folders/ww/j0vvgswj76zb_km9fdpsdpw40000gn/T/RtmpHG4pkU/remotes824f6bac619e/immunogenomics-harmony-c8f4901/DESCRIPTION’ ...
─  preparing ‘harmony’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘harmony_1.0.tar.gz’
   
Installing package into ‘/Users/xy/Library/R/4.0/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Users/xy/Library/R/4.0/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./harmony_types.h:1:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo:21:
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/compiler_check.hpp:50:4: error: "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
  #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
   ^
In file included from RcppExports.cpp:4:
In file included from ./harmony_types.h:1:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo:85:
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:149:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:150:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:151:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:161:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:162:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:163:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = true;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:173:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:174:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = true;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:175:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:185:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = true;
           ^
/Users/xy/Libraryy/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:186:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:187:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:197:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = T1::is_row;
           ^
/Users/xyg/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:198:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = T1::is_col;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:199:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = T1::is_xvec;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:209:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:210:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/Users/xy/Library/R/4.0/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:211:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘harmony’
* removing ‘/Users/xy/Library/R/4.0/library/harmony’
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/ww/j0vvgswj76zb_km9fdpsdpw40000gn/T//RtmpHG4pkU/file824f23d034c/harmony_1.0.tar.gz’ had non-zero exit status

I have tried the suggestion saying: "Create a Makevars file in the folder ~/.R (if you don't have one already), then add this line to the Makevars file: FLIBS=`gfortran -print-search-dirs | grep ^libraries: | sed 's|libraries: =||' | sed 's|:| -L|g' | sed 's|^|-L|'`"
But still the error exists. Any suggestions?

Thank you so much!

**Comment by ucsdhusky** [comment]
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.3.2 usethis_2.0.1 

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   knitr_1.31        magrittr_2.0.1   
 [4] pkgload_1.2.0     R6_2.5.0          rlang_0.4.11     
 [7] fastmap_1.1.0     tools_4.0.5       pkgbuild_1.2.0   
[10] xfun_0.22         sessioninfo_1.1.1 tinytex_0.30     
[13] cli_2.5.0         withr_2.4.2       remotes_2.2.0    
[16] htmltools_0.5.1.1 ellipsis_0.3.2    rprojroot_2.0.2  
[19] yaml_2.2.1        digest_0.6.27     lifecycle_1.0.0  
[22] crayon_1.4.1      processx_3.4.5    purrr_0.3.4      
[25] callr_3.5.1       fs_1.5.0          ps_1.6.0         
[28] curl_4.3.1        testthat_3.0.2    memoise_2.0.0    
[31] glue_1.4.2        cachem_1.0.4      evaluate_0.14    
[34] rmarkdown_2.7     compiler_4.0.5    desc_1.3.0       
[37] prettyunits_1.1.1

**Comment by ilyakorsunsky** [comment]
Dear @ucsdhusky, 

Harmony is now available on CRAN! Can you please try to install it using `install.packages("harmony")` and let me know how it goes? 

Best, 
Ilya
