### ISSUE TITLE
Computation of LISI

### ISSUE THREAD

**Issue by cane11** [immunogenomics/harmony#14]
Hey,
The repo for LISI is empty and I am searching for your computation of LISI in the paper. Is there a code that you can share? Do you know of a python implementation?

Thanks!

**Comment by ilyakorsunsky** [comment]
Dear @cane11, 

The R LISI code is now available at https://github.com/immunogenomics/LISI. I currently do not have a Python implementation - let me know if you'd still like one. 

Best, 
Ilya
