### ISSUE TITLE
Bug: dims.use is not working

### ISSUE THREAD

**Issue by andreaskapou** [immunogenomics/harmony#151]
Hi,

Just to note that there is a bug in your code and the **dims.use** parameter is ignored inside the code and never subsets the embedding matrix. This was brought as an issue earlier ( #82 ). 

The issue is that you never **subset** the embedding matrix you extract with the dims.use parameter. You just need to add this line in the RunHarmony.R file (in all functions for Seurat, SCE etc):

`embedding <- embedding[, dims.use]`

for instance after line https://github.com/immunogenomics/harmony/blob/master/R/RunHarmony.R#L120 
for the Seurat specific function. 

Best,
Andreas

**Comment by lucygarner** [comment]
Has this issue been fixed? It doesn't seem like it from having a quick look at the code?

**Comment by andreaskapou** [comment]
Hi, 

No it doesn't seem to be fixed. Another approach without changing the Harmony package is to remove specific PCs from your Seurat/SinglecellExperiment object (e.g. by creating another embedding matrix `pca2`) and then setting
`reduction = 'pca2'` when calling the Harmony function.

Hope this helps :)

**Comment by lucygarner** [comment]
Great thanks @andreaskapou. I am interested in how you decide on the number of input PCs?

**Comment by andreaskapou** [comment]
Hi Lucy,

To be honest, this is really dataset and problem specific. If you have more complex dataset (e.g. more cell types) having a larger number of PCs is better so you can capture all (biological) sources of variation (e.g. cell type and/or cell cycle) and hoping that harmony will then remove technical sources of variation across your batches. I don't want to put a specific number, since as I said it is problem specific on how in depth you want to go in obtaining different cell states.

I think using tutorials from Seurat package and actually trying different number of PCs and checking if they match with existing biology would be a good starting point.

Best,
CAK

**Comment by pati-ni** [comment]
Thank you for your patience. This issue has been addressed in the new version of Harmony.
