### ISSUE TITLE
values for lambda and theta

### ISSUE THREAD

**Issue by MatsuSui** [immunogenomics/harmony#157]
I have tried harmony for batch effect correction for my single-cell RNA-seq data to intergrate tumor and normal tissues, but when I used default parameter values, I found one problem is that some tumor cells mixed with  normal cells in the same cluster.I know I can adjust parameter values such as decreasing theta and increasing lambda to seperate tumor cells from normal cells. I have a question that if there is a recommended value range for lambda and theta? Can I choose theta=0.3 ?

**Comment by lucygarner** [comment]
#24 suggests to use theta values between 0 and 4 for a single variable.

**Comment by erflynn** [comment]
@pati-ni - what are the updates to Harmony that mitigate the overcorrection?
Also - could you describe how automated lambda selection works (e.g. when set lambda=NULL)? I've tried to understand this from the code, but am finding it difficult.
