### ISSUE TITLE
Issue when running harmony on Seurat object: Expecting a single value

### ISSUE THREAD

**Issue by FloWuenne** [immunogenomics/harmony#16]
Hi Harmony developers,

thanks for the great package, really enjoy how easy and fast it is to plug harmony into existing Seurat pipelines. 

I used harmony previously to align cells from different genotypes with success. I now wanted to integrate cells sampled at different developmental time points. My seurat object has all the processing needed and the variable is encoded as a character in the meta.data table. I also tried running it as factor but got the same error. 

Im running harmony like this:

`expression_seurat_final_test <- RunHarmony(expression_seurat_final, "Age")`

and get the following cryptic error:

`Starting harmony
Using top 50 PCs
Error in harmonyObj$setup(pc_mat, phi, Pr_b, sigma, theta, max.iter.cluster,  : 
  Expecting a single value: [extent=49].`

The error clearly seems to come from the following call of the HarmonyMatrix function but I could not figure out what is causing it exactly:

https://github.com/immunogenomics/harmony/blob/6f071627f4caf7fc24935e5f2c47ea037399ea4d/R/utils.R#L106

I would highly appreciate some help with this problem! 

Thanks in advance,

Florian

**Comment by ilyakorsunsky** [comment]
Dear @FloWuenne, 

Are you still having this issue? I made several improvements to make the software more robust. If it's still a problem, please let me know. a

Thanks for your patience!

Best, 
Ilya

**Comment by FloWuenne** [comment]
Dear @ilyakorsunsky ,

I have now tested my dataset with the Harmony vignette for Seurat V3 and it worked without a problem. 

Thanks for all the great improvements! 

Best,

Florian
