### ISSUE TITLE
Usage with big datasets (>2 M cells)

### ISSUE THREAD

**Issue by erosix** [immunogenomics/harmony#161]
Hello, 
did someone tried to use Harmony on merged objects including more than 200 samples and more than 2 M cells?
Which merging and normalization approach is suggested? And which Harmony parameters?

Using SCT transformation on the single samples and trying to merge all of them is extremely memory intensive (>500 GB memory), any suggestion on how to proceed?

**Comment by SeadonXing** [comment]
I also want to know how to adjust harmony for big data sets.

**Comment by pati-ni** [comment]
Hi @erosix,

sorry for the late reply. we have optimized the new version of harmony and is perfectly capable to handle the numbers you are quoting. Memory should not be an issue as far as harmony is concerned should take around 10GB. Make sure the other steps of your workflow are not consuming too much memory.

That said, analyzing this number of cells comes with some challenges to achieve the desire outcome may not be trivial but that very much depends on the nature of your dataset.
