### ISSUE TITLE
install issues *** stack smashing detected ***

### ISSUE THREAD

**Issue by alikhuseynov** [immunogenomics/harmony#163]
Hi there, thanks for developing this nice package. I'm trying to install it on conda env under R 4.2.1 (tried both via `devtools()` and `install.packages()` ) below is the error:

```
✔  checking for file ‘/tmp/RtmpvxuIyB/remotes4bde42326203/immunogenomics-harmony-6866e01/DESCRIPTION’ (410ms)
─  preparing ‘harmony’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘harmony_0.1.0.tar.gz’
   
* installing *source* package ‘harmony’ ...
** using staged installation
** libs

/opt/rh/devtoolset-7/root/bin/g++ -std=gnu++11 -I"/envs/spatial_v3/lib/R/include" -DNDEBUG  -I'/envs/spatial_v3/lib/R/library/Rcpp/include' -I'/envs/spatial_v3/lib/R/library/RcppArmadillo/include' -I'/envs/spatial_v3/lib/R/library/RcppProgress/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /envs/spatial_v3/include -I/envs/spatial_v3/include -Wl,-rpath-link,/envs/spatial_v3/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /envs/spatial_v3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1660164760553/work=/usr/local/src/conda/r-base-4.1.3 -fdebug-prefix-map=/envs/spatial_v3=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
/opt/rh/devtoolset-7/root/bin/g++ -std=gnu++11 -I"/envs/spatial_v3/lib/R/include" -DNDEBUG  -I'/envs/spatial_v3/lib/R/library/Rcpp/include' -I'/envs/spatial_v3/lib/R/library/RcppArmadillo/include' -I'/envs/spatial_v3/lib/R/library/RcppProgress/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /envs/spatial_v3/include -I/envs/spatial_v3/include -Wl,-rpath-link,/envs/spatial_v3/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /envs/spatial_v3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1660164760553/work=/usr/local/src/conda/r-base-4.1.3 -fdebug-prefix-map=/envs/spatial_v3=/usr/local/src/conda-prefix  -c harmony.cpp -o harmony.o
/opt/rh/devtoolset-7/root/bin/g++ -std=gnu++11 -shared -L/envs/spatial_v3/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/envs/spatial_v3/lib -Wl,-rpath-link,/envs/spatial_v3/lib -L/envs/spatial_v3/lib -o harmony.so RcppExports.o harmony.o -llapack -lblas -lgfortran -lm -lquadmath -L/envs/spatial_v3/lib/R/lib -lR
installing to /envs/spatial_v3/lib/R/library/00LOCK-harmony/00new/harmony/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** stack smashing detected ***: /envs/spatial_v3/lib/R/bin/exec/R terminated
======= Backtrace: =========
/lib64/libc.so.6(__fortify_fail+0x37)[0x2abb84e9d7a7]
/lib64/libc.so.6(+0x118762)[0x2abb84e9d762]
```

However could install it under R 4.1.3 via `conda install -c bioconda r-harmony` this does not work for `r-base=4.2.1`

Any suggestions? 
Many Thanks

**Comment by swarrd** [comment]
I had a similar issue trying to install Harmony under r 4.2.1. Output script: 

Downloading GitHub repo immunogenomics/harmony@HEAD
✔  checking for file ‘/private/var/folders/dw/xkmd_52514nb_btchbc91g9jqlp_jn/T/RtmpFvhBlI/remotes16c563e5552d8/immunogenomics-harmony-6866e01/DESCRIPTION’ ...
─  preparing ‘harmony’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘harmony_0.1.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
/usr/local/gfortran/bin/g++ -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -fPIC  -g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe -c RcppExports.cpp -o RcppExports.o
/usr/local/gfortran/bin/g++ -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -fPIC  -g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe -c harmony.cpp -o harmony.o
harmony.cpp: In member function ‘void harmony::init_cluster_cpp(unsigned int)’:
harmony.cpp:69:18: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
   69 |   if (C > 0 && C < K) {
      |                ~~^~~
harmony.cpp: In member function ‘CUBETYPE harmony::moe_ridge_get_betas_cpp()’:
harmony.cpp:236:26: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  236 |   for (unsigned k = 0; k < K; k++) {
      |                        ~~^~~
/usr/local/gfortran/bin/g++ -fopenmp -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib -o harmony.so RcppExports.o harmony.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-harmony/00new/harmony/libs
** R
** data
*** moving datasets to lazyload DB
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
Warning: namespace ‘rgdal’ is not available and has been replaced
by .GlobalEnv when processing object ‘cell_lines_small_seurat_v3’
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1: 94150 Abort trap: 6           R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/dw/xkmd_52514nb_btchbc91g9jqlp_jn/T//RtmpsVpotS/file16f84378d9df'
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/harmony’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/dw/xkmd_52514nb_btchbc91g9jqlp_jn/T//RtmpFvhBlI/file16c5653b202e0/harmony_0.1.0.tar.gz’ had non-zero exit status

**Comment by alikhuseynov** [comment]
@swarrd  in your case it's slightly different error. You might need to install `rgdal` as well. The  `Abort trap: 6..` error is probably related to `Xcode` version, not sure.

**Comment by alikhuseynov** [comment]
@swarrd and others users, I could install it under R 4.2.1 using `r-harmony` from `bioconda`.  (Note I'm using `conda` environment)
Dirty solution but it works and `harmony` runs smoothly:
- check install files at [bioconda](https://anaconda.org/bioconda/r-harmony/files) 
- download file for your OS, eg `wget https://anaconda.org/bioconda/r-harmony/0.1/download/linux-64/r-harmony-0.1-r41h9f5acd7_3.tar.bz2`
- unzip files:
	- `bunzip2 r-harmony-0.1-r41h9f5acd7_3.tar.bz2`
	- `tar -xvf r-harmony-0.1-r41h9f5acd7_3.tar `
- folders `lib/` & `info/` should appear, `cd info/recipe/`
- modify files separately: `nano meta.yaml` look for `r-base` versions and change to `4.2.1`, same for `nano conda_build_config.yaml`
- zip back the folders: `tar -czvf r-harmony-0.1-r41h9f5acd7_3.tar lib/ info/` and `bzip2 r-harmony-0.1-r41h9f5acd7_3.tar` 
- `mamba install r-harmony-0.1-r41h9f5acd7_3.tar.bz2` or `conda install r-harmony-0.1-r41h9f5acd7_3.tar.bz2` if no `mamba` available. 
- check if it loads: `R -e 'library(harmony)'`

hope this helps!
