### ISSUE TITLE
 can harmony integrate 10X and Smart-Seq2 derived data?

### ISSUE THREAD

**Issue by bijuissacch224610** [immunogenomics/harmony#164]
Hi
I am trying to integrate 2 different datasets derived from 10X and Smart-Seq2 technology respectively using harmony. Somehow the results is not great. I was wondering if you have a previous successful use case like this? I am trying to understand the QC process prior to harmony between a gene matrix data and seurat object data. 

Thanks
-Biju

**Comment by lucygarner** [comment]
Yes, this is shown in the publication.

**Comment by Moloch0** [comment]
Does that work? I am also trying to integrate 10x and smart-seq.
I meet a strange problem.The outcome of `Run harmony` is the same as `RunPCA`

**Comment by pati-ni** [comment]
@Moloch0 If this is still a problem, please post extra information where harmony v1.2 (from GitHub is used)
