### ISSUE TITLE
Error in harmonyObj$cluster_cpp()

### ISSUE THREAD

**Issue by Qirongmao97** [immunogenomics/harmony#169]
When I ran my Seurat data, I got error like this:

```
pbmc <- RunHarmony(pbmc, "orig.ident", plot_convergence = TRUE)
Harmony 1/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in harmonyObj$cluster_cpp() : 
  element-wise pow(): incompatible matrix dimensions: 92x3 and 3x1
```

I also ran the data from Harmony tutorial, I got the same error.

**Comment by Qirongmao97** [comment]
I re-install harmony by devtools::install_github("immunogenomics/harmony") but still got the error

**Comment by Famingzhao** [comment]
> 

I guess it is attributable to Matrix 1.5-1

**Comment by Qirongmao97** [comment]
> > 
> 
> I guess it is attributable to Matrix 1.5-1

I uninstalled the Matrix package but the function still not working.

**Comment by Qirongmao97** [comment]
> > 
> 
> I guess it is attributable to Matrix 1.5-1

Also tried downgrading Matrix to 1.5-0, same error.

**Comment by Matthew1309** [comment]
I'm also getting this issue, any resolution?

**Comment by Famingzhao** [comment]
No, it is owe to Matrix 1.5+. Now newnest version seurat and others packages are updated to fit  and need Matix 1.5+. However, harmony seemed not suitable with Matix 1.5+, including 1.5-0.

**Comment by Famingzhao** [comment]
My windows computer Matrix is 1.3+, which do well with harmony. But in Linux Matrix  is 1.5+, failed to run harmony. So I guess it is attributable to Matrix 1.5+. What is the version of your Matrix if you are failed to run harmony?

**Comment by wxpbioinfo** [comment]
> 

Hi,
I'm try to use the Matrix1.3+,but the Seurat need to 1.5+,Otherwise it won't work,So Is there any other way?

**Comment by KforKuma** [comment]
Hi buddies, have you ever seen the latest pull request: https://github.com/immunogenomics/harmony/pull/165
If you problem doesnt solve after upgrade/downgrade/reinstall, please consider the question may relate to Rccp and do
`  devtools::install_github("eddelbuettel/harmony",force = TRUE)
`
which works like a charm for me.

**Comment by Qirongmao97** [comment]
> Hi buddies, have you ever seen the latest pull request: #165 If you problem isn't solved after upgrade/downgrade/reinstall, please consider the question may relate to Rccp and do ` devtools::install_github("eddelbuettel/harmony",force = TRUE)` which works like a charm for me.

Thanks!!!!!!!!!!!! It also works for me.

**Comment by Qirongmao97** [comment]
> Hi buddies, have you ever seen the latest pull request: #165 If you problem isn't solved after upgrade/downgrade/reinstall, please consider the question may relate to Rccp and do ` devtools::install_github("eddelbuettel/harmony",force = TRUE)` which works like a charm for me.

Thanks!!!!!!!!!!!! It also works for me.

**Comment by wxpbioinfo** [comment]
> Hi buddies, have you ever seen the latest pull request: #165 If you problem isn't solved after upgrade/downgrade/reinstall, please consider the question may relate to Rccp and do ` devtools::install_github("eddelbuettel/harmony",force = TRUE)` which works like a charm for me.

Very Thank you!
It works!!

**Comment by Famingzhao** [comment]
> Hi buddies, have you ever seen the latest pull request: #165 If you problem isn't solved after upgrade/downgrade/reinstall, please consider the question may relate to Rccp and do ` devtools::install_github("eddelbuettel/harmony",force = TRUE)` which works like a charm for me.

I did ` devtools::install_github("eddelbuettel/harmony",force = TRUE)` . But another BUG is followed:
![image](https://user-images.githubusercontent.com/79517714/195786994-26f2c275-b41a-4e77-a324-44fb37445d12.png)

**Comment by Famingzhao** [comment]
see https://github.com/immunogenomics/harmony/issues/170 may help
