### ISSUE TITLE
Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by EDYAC** [immunogenomics/harmony#17]
Hello everyone,
I've been trying to install Harmony, however I always get an error message saying that I don't have necessary tools to compile a package.
I'm using a macOS High Sierra version 10.13.6
I have devtool installed version 2.0.1
The R studio version is 1.1.463
And I have xcode version 10.1 installed.
Any help?

This is the error mesasge I get:

* installing *source* package ‘harmony’ ...
configure: creating ./config.status
config.status: creating src/Makevars
** libs
/usr/local/clang4/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppProgress/include" -I/usr/local/include  -DUSE_FLOAT_TYPES=0 -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
/bin/sh: /usr/local/clang4/bin/clang++: No such file or directory
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package ‘harmony’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/harmony’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/yh/bv1_9myd651grh7nsbs_3t300000gn/T//Rtmp9GBnIk/file23bf053f9a/harmony_0.1.0.tar.gz’ had non-zero exit status

Thank you

**Comment by ilyakorsunsky** [comment]
Dear @EDYAC , 

Were you able to resolve this? It looks like there may be an issue with clang, from the following line: 

/usr/local/clang4/bin/clang++

Can you check where the clang binary is installed? In terminal, you should be able to do that with "which clang". 

Thank you for your patience! 

Best, 
Ilya
