### ISSUE TITLE
no applicable method for 'Key' applied to an object of class "character"

### ISSUE THREAD

**Issue by Famingzhao** [immunogenomics/harmony#170]
![image](https://user-images.githubusercontent.com/79517714/195057196-83151b76-2443-4377-811c-929a36290cbd.png)

no applicable method for 'Key' applied to an object of class "character"

**Comment by son-pop** [comment]
I have the same problem. RunHarmony() used to work fine but now I have this error.

Any help would be greatly appreciated.
Thanks

**Comment by Famingzhao** [comment]
> I have the same problem. RunHarmony() used to work fine but now I have this error.
> 
> Any help would be greatly appreciated. Thanks
I try to revise `RunHarmony.R`，like this: 
![image](https://user-images.githubusercontent.com/79517714/195789251-fde2a874-6a15-4f45-a440-b578aebeae98.png)

Then it works well. I think this solution is ok.

**Comment by son-pop** [comment]
Thanks!

Did you also run the hashed out line?

**Comment by p4rkerw** [comment]
Here's a generic solution I use that doesn't require the RunHarmony function

```
# pull the embeddings from the seurat object (shown here as lsi embeddings)
# use a metadata column in sobj@meta.data called "gem" that corresponds to the barcode gem suffix
# to identify the sample_id
my_harmony_embeddings <- HarmonyMatrix(
  data_mat  = as.matrix(sobj@reductions$sobj_lsi@cell.embeddings),
  meta_data = sobj@meta.data,
  vars_use  = "gem",
  do_pca = FALSE
)
rownames(my_harmony_embeddings) <- rownames(sobj@reductions$sobj_lsi@cell.embeddings)

#store the harmony reduction as a custom dimensional reduction called 'harmony' in the default assay
sobj[["harmony"]] <- CreateDimReducObject(embeddings = my_harmony_embeddings, key = "harmony_", assay = DefaultAssay(sobj))
sobj <- FindNeighbors(object = sobj, reduction = "harmony", dims = 2:30)
sobj <- FindClusters(object = sobj, verbose = TRUE, algorithm = 1) # Louvain algorithm
sobj <- RunUMAP(object = sobj, reduction = "harmony", dims = 2:30)
```

**Comment by Alkhawaja95** [comment]
@p4rkerw Thank you for that solution. Was there a reason behind starting from the second PC, as in `dims = 2:30` instead of `dims = 1:30` ?

**Comment by p4rkerw** [comment]
Great question. I have been using dims = 2:30 because the first dim is correlated with sequencing depth and corrected by normalization. I've tried it both ways though and I end up with very similar annotations when the first dim is included or not.

**Comment by Alkhawaja95** [comment]
Interesting idea! I thought that since sequencing depth has been corrected for, then PC1 won't be correlated with sequencing depth anymore. It is good to know that annotations were not really affected.
