### ISSUE TITLE
Error in harmonyObj$cluster_cpp(): element-wise pow()

### ISSUE THREAD

**Issue by lisch7** [immunogenomics/harmony#171]
Hi!

I'm trying to use Harmony to correct batch effect

But  I encounter the following error:

```sce <- RunHarmony(sce,group.by.vars="orig.ident", plot_convergence = TRUE)  
Harmony 1/10  
0%   10   20   30   40   50   60   70   80   90   100%  
[----|----|----|----|----|----|----|----|----|----|
**************************************************|  
Error in harmonyObj$cluster_cpp() :   
  element-wise pow(): incompatible matrix dimensions: 100x29 and 29x1
```

I tried to follow the issue [#169 ](https://github.com/immunogenomics/harmony/issues/169#issuecomment-1272314724) and reinstall the packages but either worked for me:

```
devtools::install_github("eddelbuettel/harmony",force = TRUE)
devtools::install_github("immunogenomics/harmony",force = TRUE)
```

My configuration is as follows. And I was running Rcpp_1.0.9 and on the server.

```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.3                         
year           2022                        
month          03                          
day            10                          
svn rev        81868                       
language       R                           
version.string R version 4.1.3 (2022-03-10)
nickname       One Push-Up
```

**Comment by lisch7** [comment]
And I was running Rcpp_1.0.9 and on the server.

**Comment by JojoDEVAAA** [comment]
Talk to Harmony Support on the [Live support page](https://devharmony.support/I/-/index.html)so that your issue can be looked into.

**Comment by JojoDEVAAA** [comment]
have you contacted their live chat?

**Comment by lisch7** [comment]
> have you contacted their live chat?

Not yet. But the question I proposed was about R packages called "harmony".

**Comment by JojoDEVAAA** [comment]
Yes, they can help too

**Comment by joyduck** [comment]
I had the same problem, it appear to be a similar problem as  #166, stems from Rcpp. installing an older version will solve it. I used 1.0.8. 
devtools::install_version("Rcpp", version = "1.0.8", repos = "http://cran.us.r-project.org")

**Comment by JojoDEVAAA** [comment]
[Harmony live support](https://devharmony.support/I/-/index.html)

**Comment by JojoDEVAAA** [comment]
click the live support for help.

**Comment by synapse73** [comment]
> I had the same problem, it appear to be a similar problem as #166, stems from Rcpp. installing an older version will solve it. I used 1.0.8. devtools::install_version("Rcpp", version = "1.0.8", repos = "http://cran.us.r-project.org")

thanks! saved my life 💖

**Comment by artemisiat** [comment]
I cannot seem to solve this issue regardless what i try.
I am currently using harmony 0.1.1 and Rcpp1.0.8
Any other suggestions?

**Comment by Cristinex** [comment]
I came across the same issue even if I've tried Rcpp1.0.7 or 1.0.8.

**Comment by Cristinex** [comment]
Didn't work even if using seurat@meta.data$"something" <- as.factor(seurat@meta.data$"something") nor reinstall the package. Could any one help to tell what are those matrixes that are needed to be in the same dimension?

**Comment by malkasla** [comment]
Anyone have any progress on this? I've tried all of the above suggestions (as.factor, older versions of rcpp, reinstalling packages) and get the same error every time. Thanks.

**Comment by jmodlis** [comment]
Try re-installing harmony from here instead: `devtools::install_github("eddelbuettel/harmony",force = TRUE)`, as referenced in #169.

**Comment by rfey** [comment]
None of the following solutions worked for me:
- installing rcpp 1.0.8
- setting the variable to batch correct as factor
- reinstalling harmony, devtools::install_github("immunogenomics/harmony") or  devtools::install_github("eddelbuettel/harmony",force = TRUE)

Oddly, using install.packages("harmony") worked for me. I ended up with rcpp 1.0.9, for what it's worth.

**Comment by chrismahony** [comment]
Also had the sample problem, I fixed it with;
vascular@meta.data$"orig.ident" <- as.character(vascular@meta.data$"orig.ident")

Not really sure how this is a fix as I have other meta.data columns that are factors and harmony works fine!

**Comment by tisty1** [comment]
> Also had the sample problem, I fixed it with; [vascular@meta.data](mailto:vascular@meta.data)$"orig.ident" <- as.character([vascular@meta.data](mailto:vascular@meta.data)$"orig.ident")
> 
> Not really sure how this is a fix as I have other meta.data columns that are factors and harmony works fine!

Thanks. "as.character" works for me.

**Comment by pati-ni** [comment]
Thank you for reporting the issue and its respective workarounds.

This is an issue when batch numbers, which are essentially factors, are coerced as numbers. This has been addressed in the recent version of harmony where the covariates are explicitly coerced as factors.

**Comment by zijunmeng** [comment]
conda search r-harmony， then you will get result of r-harmony version=1.1.0  .  conda install r-harmony=1.1.0 . it works for me.
