### ISSUE TITLE
Too many small clusters found after integrating data by harmony

### ISSUE THREAD

**Issue by SeadonXing** [immunogenomics/harmony#174]
Dear harmony team,

Thank you for this great software. I used harmony several times for integrating batched samples and achieved good results. But when I recently integrate 52 samples including 34w cells in total by harmony, it gives very strange results.  The UMAP looks very mass with too many small clusters as shown below.  My question is what caused this to happen and how to solve it to make it looks reasonable. My codes are attached below, because I have used harmony several times I don't think it is caused by my codes. Are there any parameters to adjust to make it integrate reasonably?

Many thanks!

## My codes to run 
scObject is my Seurat object. SampleID is the label for each sample.

```
scObject <- NormalizeData(scObject) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA(npcs = 50, verbose = FALSE)
scObject <- RunHarmony(scObject, group.by.vars = "SampleID", dims.use =1:50, project.dim = TRUE, plot_convergence=TRUE)
scObject.integrated <- RunUMAP(scObject.integrated, reduction = "harmony", dims = 1:30)
scObject.integrated <- FindNeighbors(scObject.integrated, reduction = "harmony", dims = 1:30)
scObject.integrated <- FindClusters(scObject.integrated, resolution = 0.5)
```

![UMAP integrated by harmony](https://github.com/SeadonXing/Questions/blob/master/UMAP.harmony.PNG)

**Comment by Brawni** [comment]
I'm also having this issue? Any clues? 
Thanks!

**Comment by pati-ni** [comment]
Hi, 

an idea would be to try generating and passing fewer PCs for the correction. There has been a bug  in RunHarmony() which ignores the dims.use parameter but this was fixed in the latest version of harmony

**Comment by anemartinezlarrinaga2898** [comment]
Hello Im having the same problem, it was the issue solved?

**Comment by pati-ni** [comment]
Hi @anemartinezlarrinaga2898,

I would suggest to try the latest version 1.2 from github. If that doesn't address it we may need to do some dataset debugging.

Nikos

**Comment by anemartinezlarrinaga2898** [comment]
Hi @pati-ni I did re-install harmony and rechecked that the dimensions were being subset. However with 16 I still many small clusters after integration. I choose 16 based on the Elbow plot. However testing lower dimensions with 10 I get less small clusters so I wonder if the elbow plot is the best option, and if not how I can argue how many dimensions am I using, 

Thanks in advanced!

**Comment by pati-ni** [comment]
Thanks for letting me know. Can you post a umap of your data using the uncorrected PCAs. That will help us rule out any upstream problems.

**Comment by pati-ni** [comment]
@anemartinezlarrinaga2898 hard to comment on your choice of PC number. Share relevant information like the elbow plot and basic info about the experimental design.

**Comment by anemartinezlarrinaga2898** [comment]
@pati-ni yes sure!

Im trying to integrate three public prostate cancer dataset where I have 66 patients with two phenotypes (control and tumor). I have run it on Seurat and the data has been normalized using NormalizedData. 

The elbow plot from the PCA will be the following one: 
![Harmony_ElbowPlot_Log](https://github.com/immunogenomics/harmony/assets/80770004/bacbacb8-1494-40eb-8629-e049a06a9298)

With this Elbow plot the resolution that gives total cluster is 7 PCA dims. However I think that with this Elbow plot is to low resolutions and I have used 10 PCA I still get small cluster but not as many as I was using 16. 

Best!

**Comment by pati-ni** [comment]
Elbow plot looks a bit odd. What software are you using? Please share all the code you are using to reach here and also a UMAP with the uncorrected PCs

**Comment by anemartinezlarrinaga2898** [comment]
Im using R

The data is the merge object from the 3 datasets. Each of the have been analyzed separately and then joined and analyzed. 

`data<-readRDS("0.4_AnalisisTotal/SeuratPipeline/SeuratObject.rds")
DefaultAssay(data)<-"RNA"
integration.var<-"Patient.ID"

# 2) Integration with harmony
integration.var<-"Patient.ID"
dim.final <- Calculo.Dimensiones.PCA(data)
ElbowPlot(data, ndims = 15, reduction = "pca")
data.harmony <- RunHarmony(data,group.by.vars = integration.var,dims = 1:dim.final,plot_convergence=TRUE)
# Run UMAP 
data.harmony <- RunUMAP(data.harmony,reduction = "harmony",dims = 1:dim.final)
data.harmony <- FindNeighbors(data.harmony,reduction = "harmony",dims = 1:dim.final,graph.name = "Harmony_Log")
resolutions <- c(0.1,0.3,0.5)
data.harmony <- FindClusters(data.harmony, resolution = resolutions,graph.name = "Harmony_Log")
`

Function for estimating PCA dimensions: 
`Calculo.Dimensiones.PCA <- function(data){

  pct <- data[["pca"]]@stdev / sum(data[["pca"]]@stdev) * 100
  # Calculate cumulative percents for each PC
  cumu <- cumsum(pct)
  # Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
  co1 <- which(cumu > 90 & pct < 5)[1]
  # Determine the difference between variation of PC and subsequent PC
  co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1
  dim.final <- min(co1, co2)
  return(dim.final)}`

Here the uncorrected UMAP 
![DimPlot ByPatient](https://github.com/immunogenomics/harmony/assets/80770004/87daa353-e6c4-47f6-96aa-0b86c4175dee)
![DimPlot ByStudy](https://github.com/immunogenomics/harmony/assets/80770004/be932f5a-6d89-4515-b09f-d67c555f1dfe)

**Comment by pati-ni** [comment]
> Each of the have been analyzed separately and then joined and analyzed.

I may have misunderstood, but you need to `RunPCA()` to the merged dataset.

Also, what `dim.final` returns?

**Comment by anemartinezlarrinaga2898** [comment]
Yes you are right and it is run in the merge object, the Seurat object arleady has the PCA dimensions. 

The dim.final has the number of PCA dimensions im going to use. It comes from the function "Calculo.Dimensiones.PCA" is an unbiased way of selecting the number of PCA dimmensions. 

Best,

**Comment by pati-ni** [comment]
Glad to be helpful, feel free to reopen the issue if something else is wrong

**Comment by anemartinezlarrinaga2898** [comment]
@pati-ni sorry but the answer was not clear to me.... 

Is there anything in my workflow that might be causing the appearance of small clusters?

**Comment by pati-ni** [comment]
@anemartinezlarrinaga2898 you should try calculating the number of PCs on the merged object by running `RunPCA` again in your workflow? Harmony won't work if PCs are calculated separately.

Also, please post the UMAP with the `problem` for the record of the thread.

**Comment by anemartinezlarrinaga2898** [comment]
@anemartinezlarrinaga2898 all the code posted was with the merge object where the RunPCA was estimated. With this PCA of the merge object I estimated how many dimensions I need to use which are 16. Still are too much and the integration will not give unique clusters until using a resolution of 8. 

This is the UMAP with the problem. (PCA dims 16)
<img width="557" alt="Imagen 1" src="https://github.com/immunogenomics/harmony/assets/80770004/1892202e-e01f-4996-8717-5171d39cf7a6">

**Comment by pati-ni** [comment]
I don't see anything wrong with this UMAP. If you see a specific harmony dimension as patchy (lots of clusters), report that instead.

The rest should be up to the clustering parameters. I am no expert in `FindClusters()`, so you may have to adjust the resolution parameter to find the right number of communities. From my experience, these parameters do not correspond to a unit so there are not general rules. and it is up to the user to adjust this.

> Still are too much and the integration will not give unique clusters until using a resolution of 8.

I am not sure what `resolution=8` this means, since you show resolutions of 0.1. I guess you are referring to number of PCs?

Let me know what resolution worked for you!

**Comment by anemartinezlarrinaga2898** [comment]
It was what I was reporting, getting lots of cluster inside big clusters, but is okey. 

And yes I was meaning 8 dimensions of PCA. 

I keep it with 12 PCA dimmensions and a resolution of 0.3
