### ISSUE TITLE
RunHarmony error

### ISSUE THREAD

**Issue by gdk43** [immunogenomics/harmony#179]
Hello,
Thanks for developing an excellent tool for batch correction.

I download the data, and I'm following the vignette below the address
http://htmlpreview.github.io/?https://github.com/immunogenomics/harmony/blob/master/docs/SeuratV3.html

But there is a tiny problem in the middle of the RunHarmony function
I got an error like this

"Error in UseMethod(generic = "Key", object = object): no applicable method for 'Key' applied to an object of class "character"
Traceback"

How can I take measure this error??

![image](https://user-images.githubusercontent.com/59091518/200224065-47ca24ab-1212-4c9e-b34f-5722d6b231ca.png)

Thanks

**Comment by lufce** [comment]
I have the same issue with harmony 0.1.1 via GitHub and Seurat V4.
Traceback() showed the error occurred at line 147 in RunHarmony:
`  reduction.key <- Seurat::Key(reduction.save, quiet = TRUE)` 
I changed the line as below and it went well.
`  reduction.key <- reduction.save`

**Comment by gdk43** [comment]
Wow, Thanks a lot!!
Now, it works.
