### ISSUE TITLE
Seurat v3 support

### ISSUE THREAD

**Issue by dpcook** [immunogenomics/harmony#18]
Hi there,

I figure it's in the pipeline, but it seems that--although still in beta--Seurat v3's data structures have been decided for the full release. I'm just wondering if there's a projected timeline to support direct input of a Seurat v3.x object

David

**Comment by igordot** [comment]
It seems there is already a pull request (https://github.com/immunogenomics/harmony/pull/8), so hopefully that means soon.

**Comment by lcymcdnld** [comment]
Did either of you figure out how to apply harmony to Seurat v3 data structure? I have already been using harmony and like it very much indeed, but now that I am using Seurat v3 I am stuck! :( 

Cheers,
Lucy

**Comment by ilyakorsunsky** [comment]
Dear @dpcook, @igordot, @lcymcdnld, 

Thanks for your patience! I just pushed a beta version of Harmony that interfaces with Seurat V3 and SingleCellExperiment. If you want to try it out, you can download it with the command below. Let me know how it works! 

devtools::install_github('immunogenomics/harmony', ref = 'devel')

Check out ?RunHarmony for more documentation.

**Comment by lcymcdnld** [comment]
Thank you!!

Lucy

On 18 Apr 2019, at 20:11, ilyakorsunsky <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @dpcook<https://github.com/dpcook>, @igordot<https://github.com/igordot>, @lcymcdnld<https://github.com/lcymcdnld>,

Thanks for your patience! I just pushed a beta version of Harmony that interfaces with Seurat V3 and SingleCellExperiment. If you want to try it out, you can download it with the command below. Let me know how it works!

devtools::install_github('immunogenomics/harmony', ref = 'devel')

Check out ?RunHarmony for more documentation.

**Comment by dpcook** [comment]
This is awesome--thank you! I'll try it out shortly
