### ISSUE TITLE
max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

### ISSUE THREAD

**Issue by sailseem** [immunogenomics/harmony#184]
Dear Developer,

Just wanna ask a question, when i run the function, i got an error like this:
harmony_emb <- HarmonyMatrix(mat, meta2,vars_use=c("Sample","Group","Batch"), do_pca = TRUE)
Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

Can you help me figure that out? Thanks!!

**Comment by pati-ni** [comment]
Hi @sailseem ,

sorry for the late reply. Please compute PCA separately and pass cell embeddings to harmony. do_pca option is not supported any more.
