### ISSUE TITLE
plot_convergence explanation

### ISSUE THREAD

**Issue by MWRR** [immunogenomics/harmony#188]
Hi
Could I get an explanation of the plot as I got different plots by changing some parameters?
`covid.harmony <- RunHarmony(Seurat_object,  
                            reduction = "pca",
                            group.by.vars = "sample",
                            plot_convergence = TRUE)`
![image](https://user-images.githubusercontent.com/32444200/216217506-736ccc32-29d4-4c72-ae52-676f7905288a.png)
another run of the function:
`covid.harmony <- RunHarmony(Seurat_object, 
                            reduction = "pca",
                            group.by.vars = "sample",
                            plot_convergence = TRUE,
                            epsilon.harmony=-Inf,
                            epsilon.cluster=-Inf,
                            max.iter.harmony = 20,
                            max.iter.cluster = 20)`
![image](https://user-images.githubusercontent.com/32444200/216217828-cdd9f562-f93e-4ce8-a0e4-33c63d3ef3f9.png)

Any help with this warning:

> Warning: Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony; see ?make.names for more details on syntax validity

Thanks

**Comment by pati-ni** [comment]
Please update the package, re-run your code with the newer API and let us know what is the specific problem in your convergence plot.

Regarding the warning it is more of a Seurat issue. AFAIK Seurat v5 is not showing this warning.

**Comment by pati-ni** [comment]
Closing as stale, if issues please raise a new issue
