### ISSUE TITLE
Cannot run on ARM architecture chip's OS X system

### ISSUE THREAD

**Issue by xuemingzhang** [immunogenomics/harmony#192]
*Encountered an error while installing the Harmony package on a Mac computer with an M1 chip, the error result is as follows:*

Loading required package: **harmony**
Downloading GitHub repo immunogenomics/harmony@HEAD
── R CMD build ───────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/sl/dzs8c9n10dz8qzq29rkp07gc0000gn/T/RtmpJnSd41/remotes1355959b4ae49/immunogenomics-harmony-63ebd73/DESCRIPTION’ ...
─  preparing ‘harmony’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘harmony_0.1.1.tar.gz’
   
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
g++-12 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppProgress/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
g++-12 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppProgress/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c harmony.cpp -o harmony.o
harmony.cpp: In member function 'void harmony::init_cluster_cpp(unsigned int)':
harmony.cpp:69:18: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
   69 |   if (C > 0 && C < K) {
      |                ~~^~~
harmony.cpp: In member function 'CUBETYPE harmony::moe_ridge_get_betas_cpp()':
harmony.cpp:236:26: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  236 |   for (unsigned k = 0; k < K; k++) {
      |                        ~~^~~
g++-12 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o harmony.so RcppExports.o harmony.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/homebrew/Cellar/gcc/12.2.0 -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: -undefined dynamic_lookup may not work with chained fixups
installing to /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-harmony/00new/harmony/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1: 79470 Abort trap: 6           R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/sl/dzs8c9n10dz8qzq29rkp07gc0000gn/T//RtmpQHnvqj/file136156b4bb327'
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/harmony’
Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘harmony’
2: In i.p(...) :
  installation of package ‘/var/folders/sl/dzs8c9n10dz8qzq29rkp07gc0000gn/T//RtmpJnSd41/file1355916eca6f4/harmony_0.1.1.tar.gz’ had non-zero exit status

**Comment by akhst7** [comment]
Arm-64 binary version of Harmony is available through a CRAN depository.

**Comment by pati-ni** [comment]
Is this still an issue? We just released a new version of the software available on CRAN, and to my knowledge, it works on M1 silicon.

**Comment by pati-ni** [comment]
Let us know if this is still an issue, closing now
