### ISSUE TITLE
`dims.use` not used in `RunHarmony()`

### ISSUE THREAD

**Issue by Van1yu3** [immunogenomics/harmony#194]
Hi,

I would like to report that the `dims.use` argument is not used in the function [`RunHarmony()` ](https://github.com/immunogenomics/harmony/blob/63ebd73199b79ae0d7563425a765d76deb916fe3/R/RunHarmony.R#L109). The output of the embedding will not be affected by this argument. 

Also checked that in my Seurat object:

```
set.seed(1)
h1 <- RunHarmony(obj, group.by.vars = "orig.ident", reduction="lsi", dims.use=1:30, project.dim = F) %>% Embeddings(reduction="harmony")
set.seed(1)
h2 <- RunHarmony(obj, group.by.vars = "orig.ident", reduction="lsi", dims.use=2:40, project.dim = F) %>% Embeddings(reduction="harmony")
identical(h1, h2)
```

The output of the above code is `TRUE`.

**Comment by pati-ni** [comment]
Thanks @Van1yu3 we are working towards a fix for this

**Comment by pati-ni** [comment]
Thank you for reporting the issue. This problem has been addressed in the new version of harmony, which is available on Github.

**Comment by soheilj** [comment]
Could you please address this in Symphony as well? 
(https://raw.githubusercontent.com/immunogenomics/symphony/main/vignettes/utils_seurat.R)
