### ISSUE TITLE
scRNAseq: thoughts on merging datasets generating from different version of 10x cellranger?

### ISSUE THREAD

**Issue by ahdee** [immunogenomics/harmony#198]
I'm using Harmony + Seurat to merge a series of datasets generated from cell ranger. Unfortunately, not all sets have available fastq I can download to align. Most of my sets I have successfully generated data matrices from cell ranger 7.1 however there are few that were prior generated with version 3.1.

My question is what are your thoughts about merging sets that were generating from different version? Should I just re-align the ones I have fastq for to the lowest denominator which is 3.1 ( I'm hestitant to do this since most of the data I have is for 7.1)? 

What do you think?

**Comment by pati-ni** [comment]
Hi Ahdee,
The different versions of cellranger should not influence the count vectors much. They may, however, affect the number of cells you are getting. That said, harmony should be able to correct batch effects from these datasets if they exist.

**Comment by ilyakorsunsky** [comment]
To add to @pati-ni, I'll say that we've had this issue before and found it is always best to process your FASTQs with the same pipeline for optimal results. While the core methods of cell ranger may or may not change between different versions, the GTF that they use for gene quantification may! This causes subtle but real changes that makes integration unnecessarily more difficult. When possible, I would always realign.
