### ISSUE TITLE
Problem installing harmony

### ISSUE THREAD

**Issue by cartal** [immunogenomics/harmony#2]
Hi, 

I have been trying to install Harmony but I run into the following error (See attachment)
![screen shot 2018-11-06 at 09 28 15](https://user-images.githubusercontent.com/3297906/48054974-6891b380-e1a6-11e8-8730-28087a3663c0.png)

I'm using the lastest R version, but it looks like a bug in the code.

**Comment by ilyakorsunsky** [comment]
@cartal, I merged @wikiselev's pull request. Does the install work for you now?

**Comment by cartal** [comment]
It does, thanks @wikiselev!
