### ISSUE TITLE
Harmony on large (100M cells) mass cytometry dataset

### ISSUE THREAD

**Issue by wsteenhu** [immunogenomics/harmony#201]
First of all, thank you very much for developing this package.
I was hoping you could advise on how to run Harmony on a large mass cytometry dataset (where I aim to integrate three studies). I am currently trying to run Harmony on the 'raw' marker expression data (meaning ~40 columns with marker expression and 100M cells).
Even using 128Gb RAM and 8 threads on an HPC I get an out-of-memory error.
Is there any way to further parallelize this/run the algorithm in blocks to circumvent this issue from occurring? Any advise would be welcome.

Of note: the algorithm seems to work great and runs swiftly (15 min) on a heavily downsampled dataset consisting of 700K cells.

**Comment by pati-ni** [comment]
Hi @wsteenhu, 

we are developing version 1 of harmony which is faster and more memory efficient. It may be suitable for your use case. To better understand the bottleneck can you tell me how many batches do you have in your dataset?

**Comment by shihsama** [comment]
> First of all, thank you very much for developing this package. I was hoping you could advise on how to run Harmony on a large mass cytometry dataset (where I aim to integrate three studies). I am currently trying to run Harmony on the 'raw' marker expression data (meaning ~40 columns with marker expression and 100M cells). Even using 128Gb RAM and 8 threads on an HPC I get an out-of-memory error. Is there any way to further parallelize this/run the algorithm in blocks to circumvent this issue from occurring? Any advise would be welcome.
> 
> Of note: the algorithm seems to work great and runs swiftly (15 min) on a heavily downsampled dataset consisting of 700K cells.

How could it be like that? I also ran CyTOF data with harmony (harmonypy). But it never ran out of memory, merely rather slowly. This is because it was dense matrix,compared with scRNA-seq data.
