### ISSUE TITLE
DE analysis after Running Harmony

### ISSUE THREAD

**Issue by JS0715** [immunogenomics/harmony#202]
Hi Team,

I used harmony to integrate multiple datasets. I am wondering what's the best way to run DE analysis between disease vs control?
@ilyakorsunsky can you please share your thoughts?

Thanks!

**Comment by ilyakorsunsky** [comment]
Hi @JS0715, that's a great question that we think about often! The short answer is to use a linear (e.g. limma/lme4::lmer) or generalized linear model (e.g. deseq2/lme4::glmm) to include whatever covariates you removed during harmony integration. For a simple scenario where you have one batch variable, such as donor, you could include a one global covariate in your formula: y ~ 1 + cluster + donor. I tend to go one step beyond that and include an interaction term: y ~ 1 + cluster + donor + cluster:donor. My reasoning is that if batch effects were cell-type-specific in PCA space, they may also be cell-type-specific in gene expression space. Hope that helps!
