### ISSUE TITLE
help: over correct and umap for reductions

### ISSUE THREAD

**Issue by cmf1997** [immunogenomics/harmony#205]
hello there:
great tools for integrating single cell data !!! I've used multiple times in the past.
recently, I got three pbmc sample and I ran harmony for integration
the result of dimplot seems a bit of strange
here is the dimplot after I merge three sample
<img width="402" alt="截屏2023-09-19 17 23 35" src="https://github.com/immunogenomics/harmony/assets/59285691/d8d18bb7-cff5-4e35-a2db-446a5d676944">

and after harmony
<img width="436" alt="截屏2023-09-19 17 24 29" src="https://github.com/immunogenomics/harmony/assets/59285691/c77c862d-6120-4c70-8b1b-9ca9eda9feac">

the result cover the structure of different cluster,
also I also wondering the reductions of umap is also modified after harmony, is it batch-corrected matrix? 
any suggestions would much appreciated!

here is my code 
```
scale_cluster <- function(SeuratObject, resolution=0.8, sct = FALSE){
  if(sct){
    SeuratObject <- SCTransform(SeuratObject)
  } else{
    SeuratObject <- NormalizeData(SeuratObject, normalization.method = "LogNormalize", scale.factor = 10000)
    SeuratObject <- FindVariableFeatures(SeuratObject, selection.method = "vst", nfeatures = 2000)
    SeuratObject <- ScaleData(SeuratObject)
  }
  SeuratObject <- RunPCA(SeuratObject)

  SeuratObject <- FindNeighbors(SeuratObject, dims = 1:15)
  SeuratObject <- FindClusters(SeuratObject, resolution = resolution)

  SeuratObject <- RunUMAP(SeuratObject, dims = 1:15)

  return(SeuratObject)
}

SeuratObjectConcat <- merge(SeuratObject_list[[1]], SeuratObject_list[2:length(SeuratObject_list)])
SeuratObjectConcat <- scale_cluster(SeuratObjectConcat, resolution=0.8, sct = FALSE)
SeuratObjectConcat <- RunHarmony(SeuratObjectConcat, group.by.vars = "ID")
SeuratObjectConcat <- RunUMAP(SeuratObjectConcat, dims = 1:15, reduction = "harmony")
```

**Comment by pati-ni** [comment]
It seems as harmony overcorrects. However, it would be best to show also the PC1 PC2 which are equivalent to harmony_1 and harmony_2 after correction.

To address the issue of overcorrection, I would suggest to try the new version of harmony and set lambda to NULL which it optimizes the parameter during runtime to prevent the overcorrection from happening.
