### ISSUE TITLE
Prepare for upcoming Seurat v5 release

### ISSUE THREAD

**Issue by saketkc** [immunogenomics/harmony#209]
I am opening this issue as a notification because `harmony` is listed [here](https://cran.r-project.org/web/packages/Seurat/index.html) as a package that relies (depends/imports/suggests) on Seurat. As you may know, we recently released Seurat v5 as a beta in March of this year, with new updates for spatial, multimodal, and massively scalable analysis. For more information on updates and improvements, check out our website https://satijalab.org/seurat/.
We are now preparing to release Seurat v5 to CRAN, and plan to submit it on October 23rd. While we have tried our best to keep things backward-compatible, it is possible that updates to Seurat and SeuratObject might break your existing functionality or tests. We wanted to reach out before the new version is on CRAN, so that there's time to report issues/incompatibilities and prepare you for any changes in your code base that might be necessary.

We apologize for any disruption or inconvenience, but hope that the improvements to Seurat v5 will benefit your users going forward.
To test the upcoming release, you can install Seurat from the `seurat5` branch using the instructions available on this page: https://satijalab.org/seurat/articles/install.

Thank you!
Seurat v5 team

**Comment by pati-ni** [comment]
I just checked with our latest version. All tests pass, so hooray, good job maintaining backward-compatibility as far as harmony is concerned. Our interface uses: `Seurat::CreateDimReducObject, Seurat::DefaultAssay, Seurat::Key, Seurat::Cells, Seurat::FetchData, Seurat::Reductions and Seurat::Embeddings, Seurat::ProjectDim`. Unless any side-effects are introduced in any of these calls harmony should be fine!
