### ISSUE TITLE
New version does not respect `verbose = FALSE`

### ISSUE THREAD

**Issue by const-ae** [immunogenomics/harmony#211]
Hi, 

the new version does not seem to respect the setting `verbose = FALSE` and nonetheless prints messages:
```r
Y <- matrix(1:30, nrow = 3, ncol = 10)
group <- rep(letters[1:2], length.out = 10)
res <- harmony::RunHarmony(Y, meta_data = group, nclust = 2, verbose = FALSE)
#> Hard k-means centroids initialization
```

As far as I understand, it would be necessary to make the printing for example in [harmony.cpp#L94](https://github.com/immunogenomics/harmony/blob/master/src/harmony.cpp#L94) conditional on the value of `verbose`.

-----

In addition, I think that the `Rcout` is not ideal for printing from Rcpp anyways because you cannot suppress the messages and `Rcpp::message()` is preferred (https://github.com/RcppCore/Rcpp/issues/1145). See the following example:

```r
Rcpp::cppFunction(r"(
  int test(){
    Rcpp::Rcout << "hello\n";
    return 42;
  }                  
                
)")

suppressMessages({
  test()
})
#> hello
#> [1] 42

Rcpp::cppFunction(r"(
  int test2(){
    Rcpp::message(Rcpp::wrap("hello"));
    return 42;
  }                  
)")
suppressMessages({
  test3()
})
#> [1] 42
```

**Comment by pati-ni** [comment]
Thanks for reporting the issue. Yes, you are actually right, we will be removing this message from the c++ backend.
