### ISSUE TITLE
mutiple covariates - error number of lambdas specified

### ISSUE THREAD

**Issue by antoine4ucsd** [immunogenomics/harmony#223]
Hello
I am interested in running harmony with multiple covariates.

this works
```
RunHarmony(data, c("pid"))
```
this works
```
RunHarmony(data, c("status"))
```

this failed with the following error message:
```
RunHarmony(data, c("pid", "status"))
```
Transposing data matrix
Error in tryCatchList(expr, classes, parentenv, handlers) : 
  You specified a lambda value for each covariate but the number of lambdas specified (1) and the number of covariates (2) mismatch.

it may be obvious but I dont see how to adjust the lambdas?
thank you!

**Comment by pati-ni** [comment]
Hi @antoine4ucsd 

If you look at the manual `?RunHarmony`, there is an argument `lambda`. By default this is 1, so setting it to `c(1,1)` would do the trick? You can also set it in `lambda=NULL` in which case it will set lambdas automatically for you (beta feature).

Feel free to re-open if you run into issues.

**Comment by antoine4ucsd** [comment]
I confirm it works! thank you. (maybe for newbies like me, you can edit the vignette)
Best,
