### ISSUE TITLE
How to combine/merge three ArchRProject objects

### ISSUE THREAD

**Issue by qdong2023** [immunogenomics/harmony#229]
Hello,

I have multiple ArchRProject objects to be combined/merged. These ArchR objects were generated from different batches of arrow files/experiments, however, I don't need to do "integration" such as harmony because I have done the batch correction for their multiomic RNA datasets. So I am wondering how to simply combine/merge multiple ArchR objects or if I should import all arrow files and re-create one ArchRproject object? Any suggestion would be greatly helpful!!

Thanks!

**Comment by pati-ni** [comment]
This is not related to harmony, so I am closing as off-topic.

From what I am reading, your objects look that they correspond to different vector spaces so they should be merged with strategies like Seurat's CCA.

**Comment by qdong2023** [comment]
@pati-ni I was asking about the functions in ArchR rather than the harmony. Thanks for your reply though.
