### ISSUE TITLE
How to choose and intrepret theta value ?

### ISSUE THREAD

**Issue by ahy1221** [immunogenomics/harmony#23]
Thanks for this excellent software.
I am trying to apply harmony to my dataset , which has to handle at least two covariates. 
I was wondering that how to choose suitable theta values for different covariates and how to interpret this parameter ?

**Comment by ilyakorsunsky** [comment]
Hi @ahy1221, thanks for using Harmony! I started to address this in Issue #24. 

Apologies for the delayed response!
