### ISSUE TITLE
Merging or Combining multiple ArchRProject Objects 

### ISSUE THREAD

**Issue by qdong2023** [immunogenomics/harmony#233]
Hello ArchR developers,

I have several ArchRProject objects that require merging. These ArchR objects originate from distinct batches of arrow files and experiments from 10x multiome kits. It's important to note that I've already conducted batch correction for their multiomic RNA datasets, eliminating the need for additional integration techniques like harmony in ArchR. **I'm seeking guidance on the most straightforward approach to combine or merge these multiple ArchR objects**. Should I directly merge them, or would it be more prudent to import all arrow files and reconstruct a singular ArchRProject object? Any suggestions on the best course of action would be immensely appreciated!

Thanks!

**Comment by pati-ni** [comment]
@qdong2023 I believe the ArchR repo is hosted here: https://github.com/GreenleafLab/ArchR

This is the harmony which has nothing to do with ArchR
