### ISSUE TITLE
No Instructions for Tissues and Cell Culture Merging

### ISSUE THREAD

**Issue by DarioS** [immunogenomics/harmony#240]
Would be nice to have advice in the user guide for merging cancer tissue and patient-derived cell-culture. They aren't merging.

**Comment by pati-ni** [comment]
Should the tumor cells merge?

What about the rest of cell types, are these separated?

Can you share the objective function plot?

Have you tried higher values of theta?

**Comment by DarioS** [comment]
I am unsure if cancer cells from tissue and cell culture should merge. That is a tough biological question. I have not seen anyone else with the same kind of paired data. Is there such a data set within Broad Institute which you could try? I can't share the one which I am working on. Cell culuture contains only two cell types; cancer and cancer-associated fibroblast. Tissue contains eight cell types. Wouldn't lower values of `theta` be recommended? I want the data to merge more, not less. I tried 0.
![image](https://github.com/immunogenomics/harmony/assets/631218/24bf2fac-1245-4dca-a658-3af36a6a0d99)

**Comment by pati-ni** [comment]
Can you share UMAPs before and after the integration of the two datasets? Also, theta needs to be increased to force the cells together. Setting it to zero disables the low batch diversity penalty.

**Comment by DarioS** [comment]
Ah, O.K. increasing `theta` is the solution which leads to good mixing.
