### ISSUE TITLE
Harmony using a predefined clustering vector

### ISSUE THREAD

**Issue by tkcaccia** [immunogenomics/harmony#250]
I am using harmony for spatial transcriptomic even if it is beyond is first application idea.
I think kmeans could be not the most appropriate clustering method for harmony in spatial transcriptomic data.
Is it possible to run harmony with a clustering labeling calculated with a different method?

**Comment by pati-ni** [comment]
We are investigating use cases for spatial transcriptomics workflows. Can you elaborate why kmeans is not suitable for your use case?

**Comment by tkcaccia** [comment]
I have "priviledge" point of view since I am developing a new method for feature extraction of spatial data. I am using the DLPFC visium as benchmark dataset. The dataset is composed by 12 slides from three different subject. If I use harmony of the 4 slide of the same subject, I obtained a worse clustering than without using harmony. Comparing to single-cell data, Spatial datasets seem to have a higher level of sparse matrix. I noticed that some points probably clustered together by kmeans are shifted in a different region of PCA. I guess this could be due to an erroneous choice of the centroids.

**Comment by ilyakorsunsky** [comment]
@tkcaccia thanks for your interest in using Harmony for spatial data! I fully support @pati-ni's answers above - I'll add a few things from my own experience. 

(1) We've had much better success at running Harmony v1.2 on Visium data, especially when we use the new lambda estimation feature by setting lambda=NULL. This automatically estimates the degree of ridge regression for each Harmony cluster and in practice, leads to much more accurate integration. For benchmarking, I would also suggest using more recent technologies. The recent probe-based Visium is much more gene-dense than the original sequencing based data: https://www.10xgenomics.com/datasets?query=visium&page=1&configure%5BhitsPerPage%5D=50&configure%5BmaxValuesPerFacet%5D=1000
(2) As @pati-ni said, this requires a bit of manual work but is not hard to do if you follow the advanced tutorial (http://htmlpreview.github.io/?https://github.com/immunogenomics/harmony/blob/master/doc/detailedWalkthrough.html). At the moment, we still support soft kmeans with cosine distance with diversity penalty as the most effective clustering strategy. Therefore, we do not plan to support custom clustering at this time.

**Comment by tkcaccia** [comment]
Thank you, for your suggestions. I tried the configuration lambda=NULL but it did not give satisfactory results.
For benchmarking, I will still use the DLPFC dataset because it is the mainstream dataset used for testing unsupervised learning methods. In the DLPFC, the harmony function creates artifacts.
