### ISSUE TITLE
argument 3 matches multiple formal arguments

### ISSUE THREAD

**Issue by Guliariel** [immunogenomics/harmony#255]
Hello I am trying to runHArmony for a merged Seurat object (scATAC-like data).
I am using this command:
MYSEURATOBJ <- RunHarmony(object = MYSEURATOBJ, group.by.vars = 'dataset', reduction = 'lsi', assay.use = 'bins', project.dim = FALSE).

I receive this error: argument 3 matches multiple formal arguments

I would appreciate your suggestion how to solve this issue.
Thank you

**Comment by pati-ni** [comment]
There are two different arguments, reduction.use and reduction.save and
this is the reason you are getting this error. You need to
reduction.use='lsi'
