### ISSUE TITLE
do_scatter is defined in the vignette source code but not available 

### ISSUE THREAD

**Issue by MichaelJFlynn** [immunogenomics/harmony#260]
A new user to Harmony sees the following lines in the [vignette](http://htmlpreview.github.io/?https://github.com/immunogenomics/harmony/blob/master/doc/quickstart.html) as their first exposure to the package:

```
install.packages('harmony')
```

```
library(harmony)
```

```
data(cell_lines)
V <- cell_lines$scaled_pcs
meta_data <- cell_lines$meta_data
```

and then 

```
p1 <- do_scatter(V, meta_data, 'dataset') + 
    labs(title = 'Colored by dataset')
```

This last section fails because `do_scatter` is defined in the [source code of the vignette](https://github.com/immunogenomics/harmony/blob/f054b030b5d503e7c385dac6290604013ab9f81b/doc/quickstart.Rmd#L4) but not available to the new user in the document. This tripped me up for an hour, as I tried to track down some missing package. It would spare time for the new user for that function to be available in the document somewhere.

**Comment by pati-ni** [comment]
Solved! Thanks for your feedback
