### ISSUE TITLE
Intregrating datasets with different number of features (rows)

### ISSUE THREAD

**Issue by vbarrera** [immunogenomics/harmony#37]
Hi.

First of all, thank you for this nice software.

I'm trying to use the package to integrate the following datasets:
- 2 10x datasets with condition 1
- 2 Indrops datasets with condition 1
- 2 10x datasets with condition 2
- 2 Indrops datasets with condition 2

I want to integrate all of them and explore condition 1 vs condition 2 the resulting clusters.

Following the initial steps described in the Seurat V3 Interface, I need to join all the counts matrices. The problem that I'm facing is that the datasets have different number of rows (features). The 10x datasets don't have this problem as they have the same number. However, the Indrops differ (compared to the 10x and between conditions).

How is the recommended way to proceed? Should I use a merged_seurat object instead?

Many thanks in advance.

Best,

Victor.

**Comment by ilyakorsunsky** [comment]
Hi Victor, 

This happens a lot when combining datasets from different technologies. The short answer is to find the common set of genes and then concatenate on the shared genes. The code would look like this, but please be careful - I didn't test run this code:  

mat_list <- list(mat1, mat2, ..., matN)
genes_common <- Reduce(intersect, lapply(mat_list, row.names))
exprs_all <- Reduce(cbind, lapply(mat_list, function(x) x[genes_common, ]))

I would also be careful to check why the names don't match. Two common reasons I found are: 

1) Different genome builds. Make sure that your reads were all mapped to the same reference genome, e.g. GRCh38 or hg19. 
2) Different software used to assign gene names. For example, we found that different versions of cell ranger provided different gene names, so we had to rerun our samples with the same cell ranger version. There are software efforts, such as scumi (https://bitbucket.org/jerry00/scumi-dev/src/master/), that make preprocessing uniform across technologies.  

Hope that helps!

**Comment by vbarrera** [comment]
Thank you very much for you answer.

I'll check both of your suggestions.

**Comment by Echo226** [comment]
Thanks for the answer.
