### ISSUE TITLE
NaN when correcting for multiple covariates

### ISSUE THREAD

**Issue by bio-la** [immunogenomics/harmony#39]
Hi, thanks for the great tool! It works when I'm correcting for one variable only, but I seem to be unable to make it work with multiple variables- how many iterations to run? I tried with 10,20, and also increased the nclust to 130 or 150 (I have ~80k cells to align for some of my data) but it never reaches convergence and upon inspection, the dimensionality reduction matrix has only NaN. The PCA looks fine, i'm computing 50 PC on 2500-3000 variable genes, and using all to run harmony.
is there some optimal set of params to use when correcting for multiple covariates?
thank you!

**Comment by ilyakorsunsky** [comment]
@bio-la, I ran across this issue as well! When you specify 2 variables to integrate, do you also specify 2 theta values?

**Comment by ilyakorsunsky** [comment]
I modified the code to protect against this. 
```{r}
    if (is.null(theta)) {
        theta <- rep(2, length(vars_use))
    } else if (length(theta) != length(vars_use)) {
        stop('Please specify theta for each variable')
    }
    if (is.null(lambda)) {
        lambda <- rep(1, length(vars_use))
    } else if (length(lambda) != length(vars_use)) {
        stop('Please specify lambda for each variable')
    }    
```
