### ISSUE TITLE
Error:no DLL was created

### ISSUE THREAD

**Issue by WRui** [immunogenomics/harmony#4]
When install the package, I meet the following error, could you please help me to solve it ?
###################################
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'harmony'
* removing 'D:/R-3.5.1/library/harmony'
In R CMD INSTALL
##################################

**Comment by WRui** [comment]
Thank you very much.
Command:
R version 3.51
library(devtools)  #version 2.01
install_github("immunogenomics/harmony")
##############################################
Downloading GitHub repo immunogenomics/harmony@master
√  checking for file 'C:\Users\rui\AppData\Local\Temp\RtmpKKEdNi\remotes6ddac513d67e5\immunogenomics-harmony-89f1226/DESCRIPTION' ...
-  preparing 'harmony': (397ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'harmony_0.0.0.9000.tar.gz' (1.2s)
   
* installing *source* package 'harmony' ...
** libs
c:/Rtools/mingw_64/bin/g++  -I"D:/R-35~1.1/include" -DNDEBUG  -I"D:/R-3.5.1/library/Rcpp/include" -I"D:/R-3.5.1/library/RcppArmadillo/include" -I"D:/R-3.5.1/library/RcppProgress/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -I"D:/R-35~1.1/include" -DNDEBUG  -I"D:/R-3.5.1/library/Rcpp/include" -I"D:/R-3.5.1/library/RcppArmadillo/include" -I"D:/R-3.5.1/library/RcppProgress/include"        -O2 -Wall  -mtune=generic -c harmony.cpp -o harmony.o
In file included from harmony.cpp:2:0:
utils.h: In function 'void cosine_normalize(arma::mat&, int, bool)':
utils.h:4:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int r = 0; r < X.n_rows; r++) {
                       ^
utils.h:10:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int c = 0; c < X.n_cols; c++) {
                       ^
utils.h: In function 'arma::mat pow(arma::mat, const vec&)':
utils.h:37:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int c = 0; c < A.n_cols; c++) {
                     ^
utils.h: In function 'arma::mat merge_R(const mat&, float)':
utils.h:106:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < R_new.n_rows; i++) {
                     ^
harmony.cpp: In member function 'arma::vec harmony::set_thetas(float, float, arma::vec&)':
harmony.cpp:88:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int b = 0; b < N_b.n_rows; b++) {
                       ^
harmony.cpp: In member function 'void harmony::gmm_correct_armadillo()':
harmony.cpp:423:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int b = 0; b < Phi.n_rows; b++) {
                     ^
harmony.cpp: In member function 'bool harmony::check_convergence(int)':
harmony.cpp:312:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o harmony.dll tmp.def RcppExports.o harmony.o -LD:/R-35~1.1/bin/x64 -lR
harmony.o:harmony.cpp:(.text+0x3c97): undefined reference to `dnrm2_'
harmony.o:harmony.cpp:(.text+0x6627): undefined reference to `dasum_'
harmony.o:harmony.cpp:(.text.hot+0x32d): undefined reference to `dsyrk_'
harmony.o:harmony.cpp:(.text$_ZN4arma6op_dot10direct_dotIdEENS_14arma_real_onlyIT_E6resultEjPKS3_S7_[_ZN4arma6op_dot10direct_dotIdEENS_14arma_real_onlyIT_E6resultEjPKS3_S7_]+0x9f): undefined reference to `ddot_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi]+0x29f): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi]+0x422): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi]+0x58f): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi]+0x68f): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi]+0x81a): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_13subview_elem2IdNS_3MatIjEES4_EENS_2OpIS5_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS9_T0_S0_EEi]+0x973): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma16op_normalise_mat5applyIdEEvRNS_3MatIT_EERKS4_jj[_ZN4arma16op_normalise_mat5applyIdEEvRNS_3MatIT_EERKS4_jj]+0x5e1): undefined reference to `dnrm2_'
harmony.o:harmony.cpp:(.text$_ZN4arma16op_normalise_mat5applyIdEEvRNS_3MatIT_EERKS4_jj[_ZN4arma16op_normalise_mat5applyIdEEvRNS_3MatIT_EERKS4_jj]+0x611): undefined reference to `dasum_'
harmony.o:harmony.cpp:(.text$_ZN4arma4syrkILb0ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_[_ZN4arma4syrkILb0ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_]+0xba): undefined reference to `dsyrk_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi]+0x267): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi]+0x402): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi]+0x5f0): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi]+0x78e): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi]+0x8f0): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi]+0xa5e): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_13subview_elem2IdNS_3MatIjEES5_EENS_6op_sumEEENS2_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISD_T0_S0_EEi]+0xce0): undefined reference to `dsyrk_'
harmony.o:harmony.cpp:(.text$_ZN4arma4gemvILb1ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvPT_RKT0_PKS5_S5_S5_[_ZN4arma4gemvILb1ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvPT_RKT0_PKS5_S5_S5_]+0xb5): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma4gemvILb0ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvPT_RKT0_PKS5_S5_S5_[_ZN4arma4gemvILb0ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvPT_RKT0_PKS5_S5_S5_]+0xb5): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb0ELb1ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb0ELb1ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x16f): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb0ELb1ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb0ELb1ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x271): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb0ELb1ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb0ELb1ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x342): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb0ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb0ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x160): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb0ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb0ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x2a6): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb0ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb0ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x3a4): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_13subview_elem2IdNS_3MatIjEES5_EENS_2OpIS6_NS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISA_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_13subview_elem2IdNS_3MatIjEES5_EENS_2OpIS6_NS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISA_T0_NS_10glue_timesEEE]+0x262): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_2OpIS4_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_2OpIS4_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE]+0x1a5): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_2OpIS4_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_2OpIS4_NS_9op_htransEEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE]+0x39d): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x160): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x29c): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x366): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE]+0x1ab): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE]+0x3d8): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE]+0x5c5): undefined reference to `dsyrk_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE]+0x6a5): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_9op_htransEEES5_EEvRNS4_INT_9elem_typeEEERKNS_4GlueIS8_T0_NS_10glue_timesEEE]+0x786): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma3eOpINS_4GlueINS_2OpINS_3MatIdEENS_9op_htransEEES4_NS_10glue_timesEEENS_20eop_scalar_minus_preEEC1ERKS8_d[_ZN4arma3eOpINS_4GlueINS_2OpINS_3MatIdEENS_9op_htransEEES4_NS_10glue_timesEEENS_20eop_scalar_minus_preEEC1ERKS8_d]+0x1e3): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma3eOpINS_4GlueINS_2OpINS_3MatIdEENS_9op_htransEEES4_NS_10glue_timesEEENS_20eop_scalar_minus_preEEC1ERKS8_d[_ZN4arma3eOpINS_4GlueINS_2OpINS_3MatIdEENS_9op_htransEEES4_NS_10glue_timesEEENS_20eop_scalar_minus_preEEC1ERKS8_d]+0x427): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma3eOpINS_4GlueINS_2OpINS_3MatIdEENS_9op_htransEEES4_NS_10glue_timesEEENS_20eop_scalar_minus_preEEC1ERKS8_d[_ZN4arma3eOpINS_4GlueINS_2OpINS_3MatIdEENS_9op_htransEEES4_NS_10glue_timesEEENS_20eop_scalar_minus_preEEC1ERKS8_d]+0x615): undefined reference to `dsyrk_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE]+0x22b): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE]+0x4dc): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE]+0x7c2): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_3MatIdEENS_6op_sumEEENS3_INS_3ColIdEENS_9op_htransEEEEEvRNS4_INT_9elem_typeEEERKNS_4GlueISC_T0_NS_10glue_timesEEE]+0x89e): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_[_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_]+0x189): undefined reference to `dgemm_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_[_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_]+0x37d): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_[_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_]+0x44e): undefined reference to `dgemv_'
harmony.o:harmony.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_[_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_]+0x510): undefined reference to `dsyrk_'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'harmony'
* removing 'D:/R-3.5.1/library/harmony'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/rui/AppData/Local/Temp/RtmpKKEdNi/file6ddac5a571697/harmony_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by ilyakorsunsky** [comment]
@WRui It looks like the linker is not able to find the BLAS/LAPACK functions. Can you try installing from the branch below? I included a Makevars.win file to have Harmony compile against BLAS and LAPACK libraries. 

devtools::install_github("immunogenomics/harmony", ref = "mixture_of_experts")

**Comment by WRui** [comment]
I successfully installed the package by running the command "devtools::install_github("immunogenomics/harmony", ref = "mixture_of_experts")". Thank you so much.

**Comment by WRui** [comment]
Hi, I succefully installed it but when run it, I still meet the following error.  Epithelial is a Seurat object . 
#############
Epithelial <- RunHarmony(Epithelial,"Batch")
Starting harmony
Using top 20 PCs
Error in cpp_object_initializer(.self, .refClassDef, ...) : 
  could not find function "cpp_object_initializer"

**Comment by privefl** [comment]
Can we know how this has been solved?
I run in similar issues.
