### ISSUE TITLE
Issue creating new harmony c++ object with Rcpp module

### ISSUE THREAD

**Issue by timoast** [immunogenomics/harmony#43]
Hi, I'm running into an error when trying to call `HarmonyMatrix` in another package:

```r
Error in cpp_object_initializer(.self, .refClassDef, ...) : 
  could not find function "cpp_object_initializer"
```

This seems to be due to an issue with Rcpp, see https://github.com/RcppCore/Rcpp/issues/168 for an explanation. Adding `import(methods,Rcpp)` to the NAMESPACE file fixes the problem.

**Comment by ilyakorsunsky** [comment]
Thanks for the heads up @timoast! I added the line you suggested to the NAMESPACE.
