### ISSUE TITLE
Imputing 'Corrected' Data

### ISSUE THREAD

**Issue by whitleyo** [immunogenomics/harmony#47]
This might be a naive question, but since harmony typically is not used to correct data in the original input space (i.e. gene expression) and instead works with PCA embeddings, I'm wondering if it would be appropriate to attempt to impute gene expression based off of the new embedding coordinates and the original PCA loadings (i.e. E*L, where E is an mxp matrix of m cells and p PCs, and L is a pxn matrix of loadings for the p PCs and n genes).

**Comment by ilyakorsunsky** [comment]
Dear @whitleyo, 

In principle, that is a great idea! However, I have not tried yet to re-impute the data from corrected PCs and would not yet recommend this. I am working on a separate method to model and correct the raw UMIs. 

Best, 
Ilya
