### ISSUE TITLE
Seurat RunHarmony: reduction.save does not work

### ISSUE THREAD

**Issue by ersgupta** [immunogenomics/harmony#49]
Hi, it seems reduction.save does not work when using RunHarmony. I get the following error when I try to use something other than "harmony" for reduction.save.
```
Error in `[[.Seurat`(object, reduction) : 
  Cannot find 'harmony' in this Seurat object
```
Upon checking the code I realised in RunHarmony.R 2 lines are incorrect. I think in lines 326 and 334 ```"harmony"``` should be replaced by ```reduction.save```.

**Comment by letaylor** [comment]
I ran into the same issue.

**Comment by grhogg** [comment]
Is there an update on whether this has been fixed?

**Comment by ilyakorsunsky** [comment]
Dear @ersgupta, @letaylor, and @grhogg, 

I fixed the bug with `reduction.save`. You will now be able to save multiple reductions of harmony. Please let me know if this is still a problem. Thank you for pointing out this bug and for your patience! 

Best, 
Ilya
