### ISSUE TITLE
could not find function "cpp_object_initializer"

### ISSUE THREAD

**Issue by WRui** [immunogenomics/harmony#5]
Hi, I succefully installed it but when run it, I still meet the following error. Epithelial is a Seurat object .
#############
Epithelial <- RunHarmony(Epithelial,"Batch")
Starting harmony
Using top 20 PCs
Error in cpp_object_initializer(.self, .refClassDef, ...) :
could not find function "cpp_object_initializer"

**Comment by ilyakorsunsky** [comment]
@WRui This branch should now not have that problem. Thanks for your patience!

**Comment by WRui** [comment]
Thank you so much, it now works fine.
