### ISSUE TITLE
add a release tag

### ISSUE THREAD

**Issue by EugOT** [immunogenomics/harmony#50]
Hi, I'm trying to install harmony in an Anaconda environment using the conda skeleton cran command. Unfortunately, doing so [fails unless there is at least one release for the repo](https://github.com/conda/conda/issues/6674#issuecomment-355814072). Would it be possible to [add a release](https://help.github.com/en/articles/creating-releases) to make the repo compatible with conda?

**Comment by ilyakorsunsky** [comment]
Dear @EugOT, 

I make a bare release v0.1 now. Will update as I add big features. Thanks for the suggestion! 

Best, 
Ilya
