### ISSUE TITLE
Does Harmony assume the sample cell populations are present in all samples?

### ISSUE THREAD

**Issue by lc822** [immunogenomics/harmony#51]
Hi,

Sorry if this is a naive question, but can Harmony be used in cases where only some of the cell populations are overlapping between samples, or does it assume that the same cell populations are present in all samples?

Many thanks,
Lucy

**Comment by kaizen89** [comment]
It does not assume that the same cell populations are present in all samples

**Comment by lc822** [comment]
Thank you.
