### ISSUE TITLE
Save multiple harmony reductions in Seurat object

### ISSUE THREAD

**Issue by lc822** [immunogenomics/harmony#52]
Hi,

I am a bit confused as to how I can save multiple harmony reductions in a single Seurat objects.  I thought it required me to change the "reduction.save" parameter, but I can't get this to work.

Please could you give me an example of how to do this?

Many thanks,
Lucy

**Comment by kaizen89** [comment]
Im not from harmony team. You can store different harmony reductions in seurat_object@reductions
1-RunHarmony on seurat_object
2-Store harmony reduction with a different name: 
```
seurat_object@reductions$harmony1 <- seurat_object@reductions$harmony
```
3-RunHarmony on seurat_object with different parameters and then repeat 2.
```
seurat_object@reductions$harmony2 <- seurat_object@reductions$harmony
``` 
If you want to use DimPlot using the first harmnoy reduction stored you just have to specify reduction="harmony1".
Hope it helps

**Comment by lc822** [comment]
Thank you - this didn't seem to be working for me for some reason.

**Comment by kaizen89** [comment]
If it is still not working you can try `RunHarmony` without `reduction.save` parameter and then store the reduction in
```
object@reduction$harmony1 <- object@reduction$harmony
```
You can repeat this step as needed.
Hope it helps

**Comment by lc822** [comment]
Ok great, thanks

**Comment by ilyakorsunsky** [comment]
Thanks @kaizen89 for addressing this!
