### ISSUE TITLE
Development request: Nested covariate structure

### ISSUE THREAD

**Issue by plantformatics** [immunogenomics/harmony#53]
Disclaimer: This is not an issue, rather a self-serving request for additional control over how covariates are treated during integration. I am curious if there is a plan to incorporate nested covariate structures in the model? There are occasions when an experimentalist (errrrm .... asking for a friend) did not consider the effects of separating treatment/control in separate batches. In such instances, it is desirable to remove variance between only a subset of the data points, rather than all observations. Are there any recommended strategies/tricks for tailoring harmony arguments in these situations? I have been performing separate analysis of each treatment/control (lets say different tissues) individually. The ideal situation would be to fully integrate all data into a single analysis, by effectively controlling for batch effects using a nested approach, thus conserving predetermined biological sources of variation.

Any suggestions, workarounds, or potential directions are welcome.

P.s. The ability to include numeric covariates (such as size factors) would also be nice. I promise to not overfit.

**Comment by ilyakorsunsky** [comment]
Dear @plantformatics, 

Unfortunately, I do not have an elegant solution for this situation. The best thing I would propose is to use Harmony's reference mapping functionality. For instance, if I want to avoid integrating cells from donors A and B, while integrating donors C and D, I could specify: 

```{r}
obj <- RunHarmony(obj, 'donor', reference_values=c('A', 'B'))
```

This will cluster and model all 4 donors but only remove the learned random effects for donor C and D cells. 

Note that the reference values are variable-specific. This means that if A and B are both cases and C and D are controls, then cells from A and B may get merged with C and D, removing the variation from case/ctrl status. 

```{r}
RunHarmony(obj, c('status', 'donor'), reference_values=c('A', 'B'))
````

The code below will leave cells from A and B alone entirely (and should give the same result as the first snippet above). 

```{r}
RunHarmony(obj, c('status', 'donor'), reference_values=c('case', 'A', 'B'))
````

Let me know how it goes! 

Best, 
Ilya
