### ISSUE TITLE
Where are the statistics of harmony reduction stored?

### ISSUE THREAD

**Issue by kaizen89** [immunogenomics/harmony#54]
Hi,
I'm using the wrapper RunHarmony on a seurat object on which I already performed a PCA and selected the dimensions using the ElbowPlot. Where can I find the statistics of the harmony redution so that I can choose the appropriate number of dimensions for downstream analysis?

**Comment by kaizen89** [comment]
Found
```
Stdev(object, reduction = "harmony")
```

**Comment by MMriran** [comment]
hi，i had the same question with you, and had you resolved your question？

**Comment by kaizen89** [comment]
No, I did not.

**Comment by ilyakorsunsky** [comment]
Dear @kaizen89 and @MMriran, 

The Seurat v3 wrapper RunHarmony now stores the standard deviation of the Harmonized embeddings. 

Thanks for pointing this out! 

Best, 
Ilya

**Comment by yesitsjess** [comment]
Getting the same issue after running `obj <- IntegrateLayers(object=obj, method=HarmonyIntegration, orig.reduction="pca", new.reduction="harmony")`

**Comment by rachadele** [comment]
> Getting the same issue after running `obj <- IntegrateLayers(object=obj, method=HarmonyIntegration, orig.reduction="pca", new.reduction="harmony")`

`seurat_object@reductions$harmony@stdev = as.numeric(apply(seurat_object@reductions$harmony@cell.embeddings, 2, stats::sd))`

see https://github.com/slowkow/harmonypy/issues/6#issuecomment-646681460

**Comment by jonoave** [comment]
Thanks @rachadele , was searching for an answer to this question and your suggestion totally worked!
