### ISSUE TITLE
What should I do if there are three conditions?

### ISSUE THREAD

**Issue by anyone1985** [immunogenomics/harmony#55]
Hi, 

Harmony is a great tool for me. However, my data is from three different samples with distinct treatments. What should I do when I run harmony to remove the batch effect?

Thanks!

**Comment by ilyakorsunsky** [comment]
Dear @anyone1985, 

It sounds like you have three batches, each with a different treatment. In general, no analytic approach will with certainty disentangle confounded batch and treatment. This is best addressed in experimental design. Nonetheless, your situation is probably the most common one. You can still Harmonize the 3 samples, remove variation from both batch and treatment, and find common cell types among the different conditions. Note that Harmony only affects the PCs, so the gene expression matrix will not be touched. 

Hope that helps! 

Best, 
Ilya
