### ISSUE TITLE
Random generation seeding in the interest of determinism?

### ISSUE THREAD

**Issue by ktpolanski** [immunogenomics/harmony#56]
Grats on the paper! Well deserved.

I'm trying to use Harmony in a workflow, and I'm a sucker for replicability. However, I've now ran the same data through Harmony three times, ultimately leading to three different downstream UMAP manifolds and partitions. Is there some way that I could seed whatever RNG elements Harmony uses, even if it's via a similarly ugly trick as calling `np.random.seed(0)` before calling scrublet to make that method deterministic?

EDIT: Adding the command I call, which may or may not be relevant: `hem = HarmonyMatrix(pca, batch, theta=4, verbose=FALSE, do_pca=FALSE)`, on the PCA coordinates and a batch vector ported from an AnnData object.

EDIT EDIT: Found an old issue, apparently `set.seed(1)` helps with regards to this stuff. Any chance of the remaining 10% of the way to determinism showing up soon?

**Comment by ilyakorsunsky** [comment]
Dear @ktpolanski, 

I retested Harmony with the `set.seed()` function in R and it looks like it gets you 100% towards determinism: 

```{r}
data(cell_lines_small_seurat_v3)

set.seed(1)
res1 <- RunHarmony(cell_lines_small_seurat_v3, 'dataset', verbose = FALSE)
res1 <- res1@reductions$harmony@cell.embeddings

set.seed(1)
res2 <- RunHarmony(cell_lines_small_seurat_v3, 'dataset', verbose = FALSE)
res2 <- res2@reductions$harmony@cell.embeddings

max(abs(res1 - res2))
```

Best, 
Ilya

**Comment by ktpolanski** [comment]
I've seen some minor fluctuations for a larger, ~100k cell manifold with `set.seed()`.

**Comment by ilyakorsunsky** [comment]
Do you have some reproducible example you'd be OK sharing?

**Comment by ktpolanski** [comment]
I'll see if I can get you some PCA coordinates where this demonstrably happens.

**Comment by ktpolanski** [comment]
Huh, super strange - just retrieved the PCA coordinates of an object where this was previously happening and can't reproduce it. I remember cells floating around a bit in the post-Harmony UMAP on repeated runs of the analysis pipeline. I guess keeping this open on anecdotal evidence isn't gonna cut it though, may have been something else strange happening. Sorry about the scare.

**Comment by ilyakorsunsky** [comment]
Thanks for checking on this @ktpolanski! I
