### ISSUE TITLE
404 of harmony2019

### ISSUE THREAD

**Issue by xuzhougeng** [immunogenomics/harmony#57]
I can't open page of  https://github.com/immunogenomics/harmony2019 

![image](https://user-images.githubusercontent.com/19432485/71101097-174d5380-21f1-11ea-8799-39bd96976796.png)

Is this page move to another place?

**Comment by plantformatics** [comment]
Interesting how the package authors tend to disappear after publication. I too, would like to see the scripts used in the manuscript, and wonder why they haven't been released...

**Comment by ilyakorsunsky** [comment]
Dear @xuzhougeng and @plantformatics, 

I pushed notebooks to do the analyses in figures 2-5; figure 6 is coming soon. For clarity, I showed the key steps in preprocessing, Harmony, and LISI computations. Please let me know if there are particular aspects of the analyses that you would like more details on. 

Thanks for the reminder! 

Best, 
Ilya
