### ISSUE TITLE
idx_list bug

### ISSUE THREAD

**Issue by slowkow** [immunogenomics/harmony#58]
Some of the cells are included in 2 blocks instead of 1 block.

Here's what I see when I run Harmony with 97 cells:

```
idx_min 0
idx_max 4
idx_list         0        1        2        3        4

idx_min 4
idx_max 9
idx_list         4        5        6        7        8        9

idx_min 9
idx_max 14
idx_list          9        10        11        12        13        14

idx_min 14
idx_max 19
idx_list         14        15        16        17        18        19

...

idx_min 87
idx_max 92
idx_list         87        88        89        90        91        92

idx_min 92
idx_max 96
idx_list         92        93        94        95        96
```

Notice that:
- cell 4 is included in block 1 and block 2
- cell 9 is included in block 2 and block 3
- cell 92 is included in the last two blocks
- etcetera

This probably doesn't matter too much, but I guess you intended for each cell to be included in a single block.

**Comment by ilyakorsunsky** [comment]
Thanks for taking care of this bug Kam!
