### ISSUE TITLE
Filtering of cells

### ISSUE THREAD

**Issue by catsargent** [immunogenomics/harmony#6]
Hi, 
I was wondering why you don't include filtering of cells (e.g. nGene, % mitochondrial genes) in your example Seurat workflow? 
Thanks
Catherine

**Comment by ilyakorsunsky** [comment]
Good questions, Catherine! In the example vignette, I think the cells are pre-filtered. In an ab initio, analysis, filtering would be necessary. For regressing out UMI and %MT, I am split. While I do agree that transformations to remove the effect of these factors is necessary, a global regression may not be the right way. Like regressing out discrete batch variables, this should also be done in a cell-type sensitive manner. I am working on an extension of Harmony that models these features. In this way, Harmony will simultaneously remove the effects of discrete (e.g. donor, tissue, experiment, batch) and continuous (e.g. nUMI, %MT, cell cycle state) factors from the low dimensional embedding. Hope to roll that out in the new year!

**Comment by ilyakorsunsky** [comment]
Apologies for the lateness this time, getting back into work for the new year! For most cases, I found that I get interpretable results without accounting for depth. The best practice as far as I know is to do the global scaling.
