### ISSUE TITLE
divide by zero bug

### ISSUE THREAD

**Issue by slowkow** [immunogenomics/harmony#60]
`tau` is set to 0 by default. I wonder if this snippet is working as intended?

https://github.com/immunogenomics/harmony/blob/1a6d77aae524a08a2ca91737a152ab2047ccee78/R/ui.R#L170

For the toy example, we have the following:

```
> nclust
[1] 50
> tau
[1] 0

> nclust * tau
[1] 0

> (N_b / (nclust * tau))
  half jurkat   t293 
   Inf    Inf    Inf 

> -(N_b / (nclust * tau))
  half jurkat   t293 
  -Inf   -Inf   -Inf 

> -(N_b / (nclust * tau)) ^ 2
  half jurkat   t293 
  -Inf   -Inf   -Inf 

> exp(-(N_b / (nclust * tau)) ^ 2)
  half jurkat   t293 
     0      0      0 

> 1 - exp(-(N_b / (nclust * tau)) ^ 2)
  half jurkat   t293 
     1      1      1 

> theta * (1 - exp(-(N_b / (nclust * tau)) ^ 2))
  half jurkat   t293 
     1      1      1 
```

We end up with `c(1, 1, 1)` for `theta`.

I guess you intended for the default to be `c(2, 2, 2)` instead of `c(1, 1, 1)`, right?

https://github.com/immunogenomics/harmony/blob/1a6d77aae524a08a2ca91737a152ab2047ccee78/R/ui.R#L147-L149

**Comment by ilyakorsunsky** [comment]
Although we do get that `Inf` result in the middle, this is OK. When `tau==0`, then the original `theta` is just not affected by the `tau` factor.
