### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jydong123** [immunogenomics/harmony#61]
Hello, I have the following error when trying to install harmony, thanks for looking over and the help! 

Installing package into ‘C:/Users/Jeff's PC/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'harmony' ...
** using staged installation
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c harmony.cpp -o harmony.o
harmony.cpp: In member function 'void harmony::init_cluster_cpp(unsigned int)':
harmony.cpp:69:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (C > 0 && C < K) {
                  ^
harmony.cpp: In member function 'CUBETYPE harmony::moe_ridge_get_betas_cpp()':
harmony.cpp:234:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (unsigned k = 0; k < K; k++) { 
                          ^
c:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o harmony.dll tmp.def RcppExports.o harmony.o -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lRlapack -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lR
installing to C:/Users/Jeff's PC/Documents/R/win-library/3.6/00LOCK-harmony/00new/harmony/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Jeff's PC/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c harmony.cpp -o harmony.o
harmony.cpp: In member function 'void harmony::init_cluster_cpp(unsigned int)':
harmony.cpp:69:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (C > 0 && C < K) {
                  ^
harmony.cpp: In member function 'CUBETYPE harmony::moe_ridge_get_betas_cpp()':
harmony.cpp:234:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (unsigned k = 0; k < K; k++) { 
                          ^
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o harmony.dll tmp.def RcppExports.o harmony.o -LC:/PROGRA~1/R/R-36~1.2/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-36~1.2/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-36~1.2/bin/x64 -lR
installing to C:/Users/Jeff's PC/Documents/R/win-library/3.6/00LOCK-harmony/00new/harmony/libs/x64
** R
** data
** byte-compile and prepare package for lazy loading
Error: unexpected symbol in "setwd('C:/Users/JEFF'S"
Execution halted
ERROR: lazy loading failed for package 'harmony'
* removing 'C:/Users/Jeff's PC/Documents/R/win-library/3.6/harmony'
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘C:/Users/JEFF'S~1/AppData/Local/Temp/RtmpyGV43w/file26c430c5441c/harmony_1.0.tar.gz’ had non-zero exit status

**Comment by ilyakorsunsky** [comment]
Dear @jydong123, 

From the error message above, it looks like R does not like your path name: 

`Error: unexpected symbol in "setwd('C:/Users/JEFF'S"`

I would try removing the whitespace characters from your path and see if that helps. 

Best, 
Ilya
