### ISSUE TITLE
Can Harmony accept other input instead of PCs?

### ISSUE THREAD

**Issue by connorhknight** [immunogenomics/harmony#65]
Hi, 

This is not an issue, but a question. 
Harmony takes the PCA embeddings and works with this data, do you know what would happen if another dimensionality reduction techniques is used instead? Would this make the results unreliable as harmony is tailored towards PCA embeddings? 

Kind regards,

Connor

**Comment by slowkow** [comment]
Hi Connor,

Thanks for the question. The Harmony algorithm can be applied to any numeric features, whether they are PCs, genes, or something else. In my experience, I have only tried running it on PCs. I would suggest that you try it out! If you find something interesting, you might consider sharing your results.
