### ISSUE TITLE
cannot reproduce harmony processing output

### ISSUE THREAD

**Issue by JuHey** [immunogenomics/harmony#66]
I had tried out Harmony first from within scanpy-jupyter lab framework following the notebook from the Teichman group (pancreas-5-Harmony-kBET.ipynb; see: https://github.com/Teichlab/bbknn/tree/master/examples) about a year ago (Feb 2019). Then, I could easily reproduce the batch effect correction on the said pancreas dataset and have used Harmony since then. Now, on a new system, I installed the most recent github version of Harmony and ran the same notebook. The run completed but the output looks drastically different. I tried it on other datasets on which I had applied Harmony before and I see the same differences:  it generates a large to very large number of clusters that do not integrate well or separate well. I am attaching the earlier (2019) and the recent (2020) UMAPs for review.  The relevant code that I applied:
`%%R -i pca -i batch -o hem`
`library(harmony)
library(magrittr)`
`hem <- HarmonyMatrix(pca, batch, theta=4)`
`hem = data.frame(hem)`
Where pca is X_pca from the pca step in scanpy and batch is the reference to the batch variable to be sampled. I tried different thetas (0 to 5; not shown). There is a change but it is minimal.
2019:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/36309128/72835879-86d3ba00-3c59-11ea-9ed5-09b1b1c369dd.png">
2020:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/36309128/72836218-2db85600-3c5a-11ea-9776-9124b74bdd0f.png">

I really like the fast processing that comes with Harmony. Hence, I would be interested in feedback on any changes in Harmony processing that might explain the results I observed.

**Comment by ilyakorsunsky** [comment]
Dear @JuHey, 

During the revisions, we decided to add a PCA-preprocessing step as the default behavior of HarmonyMatrix. Thus, the 2020 version you posted above re-PCA'd the input PCs. To get the original behavior back, please specify `do_pca=FALSE`:

```{r}
hem <- HarmonyMatrix(pca, batch, theta=4, do_pca=FALSE)
```

![image](https://user-images.githubusercontent.com/2343994/74854980-0bbffb00-530e-11ea-86c1-821438b00c29.png)

I'll also add that in this example, there are sources of batch from both donor and study. With Harmony, you can model and remove both for a more thorough integration. 

Finally, if you want to run Harmony in Python, you can now do it directly with @slowkow's harmonypy package (https://github.com/slowkow/harmonypy). 

Thanks for pointing out this behavior! 

Best, 
Ilya

**Comment by JuHey** [comment]
Thank you very much @ilyakorsunsky !!!
