### ISSUE TITLE
analysis of multiple time points * 2 replicates of scRNA-seq

### ISSUE THREAD

**Issue by tanasa** [immunogenomics/harmony#69]
Dear all,

'd appreciate having your suggestions on the following case of scRNAseq analysis with HARMONY /Seurat 3.1. ; the question is : what analysis strategy would you recommend (described below) ?

shall we have 4 batches of scRNA-seq data of these experiments :

**WT_batch1, WT_batch2, A_batch1, A_batch2**

**WT_batch3, WT_batch4, B_batch3, B_batch4**

what is the optimal way to analyze the data-sets ? Several analysis strategies are possible :

**STRATEGY A.**

1. to use CELLRANGER AGGR (with NORMALIZATION = TRUE) on :

**WT_batch1, WT_batch2 : to produce WT_batch_1_2**

**A_batch1, A_batch2 : to produce A_batch_1_2**

**WT_batch3, WT_batch4 : to produce WT_batch_3_4**

**B_batch3, B_batch4 : to produce B_batch_3_4**

2. and to follow the descriptions of SEURAT pipelines with HARMONY, on WT_batch_1_2, WT_batch_3_4, A_batch_1_2, B_batch_3_4 :

https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/harmony.html

**STRATEGY B.**

1. to use SEURAT **MERGE** function in order to have all the raw data (WT_batch1, WT_batch2, A_batch1, A_batch2, WT_batch3, WT_batch4, B_batch3, B_batch4) in a large MATRIX

2. could I apply **HARMONY** on all the experiments with those 2 replicates, and afterwards, how could I call the function FindMarkers in SEURAT (FindMarkers(object, ident.1, ident.2), in order to specify the REPLICATES in ident.1 and in ident.2 ?

**Any other analysis strategy ?** Any suggestions, comments would be very welcome ! Thanks a lot !

bogdan

**Comment by ilyakorsunsky** [comment]
Dear Bogdan, 

You clearly have an interesting experimental design here! I will try to offer advice with respect to Harmony and the general workflow. 

If you want a joint embedding of all 8 samples, I recommend that you put all the cells into a single matrix, normalize, scale, PCA, and then Harmonize on whatever conditions you need (e.g. batch, WT/A/B). You describe a few ways of getting all the data into 1 matrix (cell ranger aggr, Seurat Merge). All of these should work and hopefully get you to the same place: a cell by gene raw UMI count matrix. 

As you mentioned, you want to retain the different IDs of the 8 experiments for downstream analysis. This information should be stored in Seurat's `meta.data` dataframe. When you do differential expression analysis, you will use these labels. 

I hope that started to answer your questions! 

Best, 
Ilya

**Comment by tanasa** [comment]
Thanks, Ilya.
