### ISSUE TITLE
Bioconductor support - SingleCellExperiment

### ISSUE THREAD

**Issue by robertamezquita** [immunogenomics/harmony#7]
Hi, your package looks very interesting for performing data integration. I was wondering if there might be plans to submit to Bioconductor and in the process incorporate support for the SingleCellExperiment (SCE) class for more easily integrating into existing scRNA-seq workflows that rely on SCE? Thanks!

**Comment by ilyakorsunsky** [comment]
Thanks for the suggestion, @robertamezquita! Making Harmony compatible with SCE is definitely a priority but I don't have a definite timeline for it yet.

**Comment by ilyakorsunsky** [comment]
Dear @robertamezquita, 

Please check out the beta version of Harmony with support for SCE data structures. You can install it with 

devtools::install_github('immunogenomics/harmony', ref = 'devel')

There is pipeline specific documentation under ?RunHarmony. 

Best, 
Ilya

**Comment by robertamezquita** [comment]
Just wanted to comment that it would be good to add the `SCE` support front and center on the README
