### ISSUE TITLE
Harmony on CyTOF Data

### ISSUE THREAD

**Issue by EDYAC** [immunogenomics/harmony#72]
Hello everyone,
I was wondering if someone has ever used Harmony on CyTOF data? In practice, would be applicable? 
Has anyone applied it to FCS files? 
Thank you,
Edouard

**Comment by ilyakorsunsky** [comment]
Dear Edouard, 

Within our group, @nmillard10 has used Harmony successfully to integrate CyTOF datasets of immune cells across multiple tissues. In practice, I would input a normalized matrix of cells-by-proteins into the `HarmonyMatrix` function. By default, `HarmonyMatrix` will PCA your input matrix and return a matrix of cells by PCs. If you would like to avoid PCA and instead directly "correct" your cell-by-marker matrix, you can specify that with `do_pca`: 

```{r}
dim(X) ## X is a dense matrix of cells by proteins
harmony_result <- HarmonyMatrix(X, meta_data, 'batch', do_pca=FALSE)
```

If you do choose to use PCA, be careful to specify the number of PCs (`npcs`) to be fewer than the number of features: 

```{r}
ncol(X) ## number of features should exceed npcs (below)
harmony_result <- HarmonyMatrix(X, meta_data, 'batch', do_pca=TRUE, npcs=10)
```

You can run harmony on a matrix object in R or Python (https://github.com/slowkow/harmonypy). I have not worked with CyTOF data directly, so I cannot give any useful recommendations for going from an FCS file to an R or Python matrix. 

Hope this helps and thanks for giving Harmony a try! 

Best, 
Ilya
