### ISSUE TITLE
"cell_lines", "cosine_normalize" and "do_scatter"functions not installed

### ISSUE THREAD

**Issue by jiayiliujiayi** [immunogenomics/harmony#73]
Hi,  

When trying to call the "cell_lines", "cosine_normalize" or "do_scatter" function, the error was as such:  
```
Error: 'cell_lines' is not an exported object from 'namespace:harmony'
```

Check the installed functions:  
```
harmony::%>%              harmony::.__T__[:base     harmony::.__T__[[<-:base
harmony::RunHarmony       harmony::HarmonyMatrix    harmony::.__T__$<-:base
harmony::.__T__$:base     harmony::.__T__[<-:base
```

Checked the source code (./R):
These three functions are not found under this directory.  

Thank you in advance.  

Best, 
Jiayi

FYI, the [link](https://portals.broadinstitute.org/harmony/advanced.html) of the tutorial that I was following.

**Comment by nmalwinka** [comment]
I have exactly the same issue.

**Comment by cdiaz45** [comment]
Hi, when you install harmony, the datasets used in the example are included. Try data("cell_lines") and check. From going through the whole thing cosine_normalize is not really used. It only appears once. You can find the do_scatter" function in the harmony documentation (when you google it it will come up: https://github.com/immunogenomics/harmony/blob/master/vignettes/quickstart.Rmd). Source the function to your computer (or copy directly into your session). I hope this helps.

**Comment by zyb1984** [comment]
but what about cosine_normalize function ? It  also not included in the vignettes

**Comment by Y-CBob** [comment]
> but what about cosine_normalize function ? It also not included in the vignettes

same here, super frustrating...

**Comment by jiw181** [comment]
same here. installed harmony_0.1.1 with biocmanager, could not find function "do_scatter"

**Comment by zhiliqiao** [comment]
For function `cosine_normalize`, it should be an L2 normalization function as below:
`cosine_normalize = function(x, dim){
  apply(x, MARGIN = dim, function(a) a / sqrt(sum(a^2)))
}`

**Comment by brianjohnhaas** [comment]
do_scatter isn't there...   Maybe this is old documentation?
https://portals.broadinstitute.org/harmony/articles/quickstart.html
