### ISSUE TITLE
Can "harmony" be used in conjunction with "monocle"

### ISSUE THREAD

**Issue by yuGithuuub** [immunogenomics/harmony#74]
Hello, thank you very much for providing such a useful tool "harmony".
I am a rookie in R,I have encountered a problem and would like to ask.

Harmony created an "my_harmony_embeddings“ object.
When I want to use monocle for trajectory inference,I don't know how to create the input file using the “my_harmony_embeddings".

How can I solve such a problem?

Thanks for your answer ^o^

**Comment by ilyakorsunsky** [comment]
Dear @yuGithuuub, 

I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding. 

```{r}
library(DDRTree)
get_ddr <- function(harmony_Z, ndim=2) {
    ncells <- nrow(harmony_Z)
    ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
    ddr_args <- c(list(
        X = harmony_Z, 
        dimensions = ndim, ## LOW DIMENSIONALITY
        ncenter = ncenter, 
        verbose = FALSE))
    ddrtree_res <- do.call(DDRTree, ddr_args)
    ddrtree_res$Z <- t(ddrtree_res$Z)
    row.names(ddrtree_res$Z) <- row.names(harmony_Z)
    colnames(ddrtree_res$Z) <- colnames(harmony_Z)
    return(ddrtree_res$Z)
}
```
In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space." 

Best, 
Ilya

**Comment by yuGithuuub** [comment]
Thank you very much for your help, this is very good news
^o^

**Comment by Emma-1991** [comment]
> Dear @yuGithuuub,
> 
> I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> 
> ```
> library(DDRTree)
> get_ddr <- function(harmony_Z, ndim=2) {
>     ncells <- nrow(harmony_Z)
>     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
>     ddr_args <- c(list(
>         X = harmony_Z, 
>         dimensions = ndim, ## LOW DIMENSIONALITY
>         ncenter = ncenter, 
>         verbose = FALSE))
>     ddrtree_res <- do.call(DDRTree, ddr_args)
>     ddrtree_res$Z <- t(ddrtree_res$Z)
>     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
>     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
>     return(ddrtree_res$Z)
> }
> ```
> 
> In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> 
> Best,
> Ilya

Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask.
Here are my code and error:
> harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> harmony_embedding[seq_len(5), seq_len(5)]
                                                 harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> get_ddr <- function(harmony_Z, ndim=2) {
>     ncells <- nrow(harmony_Z)
>     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
>     ddr_args <- c(list(
>         X = harmony_Z, 
>         dimensions = ndim, ## LOW DIMENSIONALITY
>         ncenter = ncenter, 
>         verbose = FALSE))
>     ddrtree_res <- do.call(DDRTree, ddr_args)
>     ddrtree_res$Z <- t(ddrtree_res$Z)
>     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
>     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
>     return(ddrtree_res$Z)
> }
> get_ddr(harmony_embedding)
Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
  Error: ncenters must be greater than or equal to ncol(X)

How can I solve such a problem?
Thanks for your answer !

**Comment by ouyang199409** [comment]
> > Dear @yuGithuuub,
> > I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> > ```
> > library(DDRTree)
> > get_ddr <- function(harmony_Z, ndim=2) {
> >     ncells <- nrow(harmony_Z)
> >     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> >     ddr_args <- c(list(
> >         X = harmony_Z, 
> >         dimensions = ndim, ## LOW DIMENSIONALITY
> >         ncenter = ncenter, 
> >         verbose = FALSE))
> >     ddrtree_res <- do.call(DDRTree, ddr_args)
> >     ddrtree_res$Z <- t(ddrtree_res$Z)
> >     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> >     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> >     return(ddrtree_res$Z)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> > Best,
> > Ilya
> 
> Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask. Here are my code and error:
> 
> > harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> > harmony_embedding[seq_len(5), seq_len(5)]
> > harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
> > Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
> > Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
> > Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
> > Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
> > Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> > get_ddr <- function(harmony_Z, ndim=2) {
> > ncells <- nrow(harmony_Z)
> > ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > ddr_args <- c(list(
> > X = harmony_Z,
> > dimensions = ndim, ## LOW DIMENSIONALITY
> > ncenter = ncenter,
> > verbose = FALSE))
> > ddrtree_res <- do.call(DDRTree, ddr_args)
> > ddrtree_res$Z <- t(ddrtree_res$Z)
> > row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > return(ddrtree_res$Z)
> > }
> > get_ddr(harmony_embedding)
> > Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
> > Error: ncenters must be greater than or equal to ncol(X)
> 
> How can I solve such a problem? Thanks for your answer !


> > Dear @yuGithuuub,
> > I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> > ```
> > library(DDRTree)
> > get_ddr <- function(harmony_Z, ndim=2) {
> >     ncells <- nrow(harmony_Z)
> >     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> >     ddr_args <- c(list(
> >         X = harmony_Z, 
> >         dimensions = ndim, ## LOW DIMENSIONALITY
> >         ncenter = ncenter, 
> >         verbose = FALSE))
> >     ddrtree_res <- do.call(DDRTree, ddr_args)
> >     ddrtree_res$Z <- t(ddrtree_res$Z)
> >     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> >     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> >     return(ddrtree_res$Z)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> > Best,
> > Ilya
> 
> Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask. Here are my code and error:
> 
> > harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> > harmony_embedding[seq_len(5), seq_len(5)]
> > harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
> > Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
> > Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
> > Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
> > Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
> > Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> > get_ddr <- function(harmony_Z, ndim=2) {
> > ncells <- nrow(harmony_Z)
> > ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > ddr_args <- c(list(
> > X = harmony_Z,
> > dimensions = ndim, ## LOW DIMENSIONALITY
> > ncenter = ncenter,
> > verbose = FALSE))
> > ddrtree_res <- do.call(DDRTree, ddr_args)
> > ddrtree_res$Z <- t(ddrtree_res$Z)
> > row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > return(ddrtree_res$Z)
> > }
> > get_ddr(harmony_embedding)
> > Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
> > Error: ncenters must be greater than or equal to ncol(X)
> 
> How can I solve such a problem? Thanks for your answer !

I meet the same problem. Have you solved it?

**Comment by YogiBud** [comment]
> > > Dear @yuGithuuub,
> > > I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> > > ```
> > > library(DDRTree)
> > > get_ddr <- function(harmony_Z, ndim=2) {
> > >     ncells <- nrow(harmony_Z)
> > >     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > >     ddr_args <- c(list(
> > >         X = harmony_Z, 
> > >         dimensions = ndim, ## LOW DIMENSIONALITY
> > >         ncenter = ncenter, 
> > >         verbose = FALSE))
> > >     ddrtree_res <- do.call(DDRTree, ddr_args)
> > >     ddrtree_res$Z <- t(ddrtree_res$Z)
> > >     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > >     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > >     return(ddrtree_res$Z)
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> > > Best,
> > > Ilya
> > 
> > 
> > Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask. Here are my code and error:
> > > harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> > > harmony_embedding[seq_len(5), seq_len(5)]
> > > harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
> > > Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
> > > Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
> > > Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
> > > Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
> > > Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> > > get_ddr <- function(harmony_Z, ndim=2) {
> > > ncells <- nrow(harmony_Z)
> > > ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > > ddr_args <- c(list(
> > > X = harmony_Z,
> > > dimensions = ndim, ## LOW DIMENSIONALITY
> > > ncenter = ncenter,
> > > verbose = FALSE))
> > > ddrtree_res <- do.call(DDRTree, ddr_args)
> > > ddrtree_res$Z <- t(ddrtree_res$Z)
> > > row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > > colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > > return(ddrtree_res$Z)
> > > }
> > > get_ddr(harmony_embedding)
> > > Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
> > > Error: ncenters must be greater than or equal to ncol(X)
> > 
> > 
> > How can I solve such a problem? Thanks for your answer !
> 
> > > Dear @yuGithuuub,
> > > I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> > > ```
> > > library(DDRTree)
> > > get_ddr <- function(harmony_Z, ndim=2) {
> > >     ncells <- nrow(harmony_Z)
> > >     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > >     ddr_args <- c(list(
> > >         X = harmony_Z, 
> > >         dimensions = ndim, ## LOW DIMENSIONALITY
> > >         ncenter = ncenter, 
> > >         verbose = FALSE))
> > >     ddrtree_res <- do.call(DDRTree, ddr_args)
> > >     ddrtree_res$Z <- t(ddrtree_res$Z)
> > >     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > >     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > >     return(ddrtree_res$Z)
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> > > Best,
> > > Ilya
> > 
> > 
> > Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask. Here are my code and error:
> > > harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> > > harmony_embedding[seq_len(5), seq_len(5)]
> > > harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
> > > Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
> > > Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
> > > Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
> > > Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
> > > Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> > > get_ddr <- function(harmony_Z, ndim=2) {
> > > ncells <- nrow(harmony_Z)
> > > ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > > ddr_args <- c(list(
> > > X = harmony_Z,
> > > dimensions = ndim, ## LOW DIMENSIONALITY
> > > ncenter = ncenter,
> > > verbose = FALSE))
> > > ddrtree_res <- do.call(DDRTree, ddr_args)
> > > ddrtree_res$Z <- t(ddrtree_res$Z)
> > > row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > > colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > > return(ddrtree_res$Z)
> > > }
> > > get_ddr(harmony_embedding)
> > > Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
> > > Error: ncenters must be greater than or equal to ncol(X)
> > 
> > 
> > How can I solve such a problem? Thanks for your answer !
> 
> I meet the same problem. Have you solved it?




Anyone solved this yet?

**Comment by NiannianSoHungry** [comment]
> > > > Dear @yuGithuuub,
> > > > I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> > > > ```
> > > > library(DDRTree)
> > > > get_ddr <- function(harmony_Z, ndim=2) {
> > > >     ncells <- nrow(harmony_Z)
> > > >     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > > >     ddr_args <- c(list(
> > > >         X = harmony_Z, 
> > > >         dimensions = ndim, ## LOW DIMENSIONALITY
> > > >         ncenter = ncenter, 
> > > >         verbose = FALSE))
> > > >     ddrtree_res <- do.call(DDRTree, ddr_args)
> > > >     ddrtree_res$Z <- t(ddrtree_res$Z)
> > > >     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > > >     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > > >     return(ddrtree_res$Z)
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> > > > Best,
> > > > Ilya
> > > 
> > > 
> > > Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask. Here are my code and error:
> > > > harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> > > > harmony_embedding[seq_len(5), seq_len(5)]
> > > > harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
> > > > Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
> > > > Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
> > > > Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
> > > > Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
> > > > Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> > > > get_ddr <- function(harmony_Z, ndim=2) {
> > > > ncells <- nrow(harmony_Z)
> > > > ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > > > ddr_args <- c(list(
> > > > X = harmony_Z,
> > > > dimensions = ndim, ## LOW DIMENSIONALITY
> > > > ncenter = ncenter,
> > > > verbose = FALSE))
> > > > ddrtree_res <- do.call(DDRTree, ddr_args)
> > > > ddrtree_res$Z <- t(ddrtree_res$Z)
> > > > row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > > > colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > > > return(ddrtree_res$Z)
> > > > }
> > > > get_ddr(harmony_embedding)
> > > > Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
> > > > Error: ncenters must be greater than or equal to ncol(X)
> > > 
> > > 
> > > How can I solve such a problem? Thanks for your answer !
> > 
> > 
> > > > Dear @yuGithuuub,
> > > > I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> > > > ```
> > > > library(DDRTree)
> > > > get_ddr <- function(harmony_Z, ndim=2) {
> > > >     ncells <- nrow(harmony_Z)
> > > >     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > > >     ddr_args <- c(list(
> > > >         X = harmony_Z, 
> > > >         dimensions = ndim, ## LOW DIMENSIONALITY
> > > >         ncenter = ncenter, 
> > > >         verbose = FALSE))
> > > >     ddrtree_res <- do.call(DDRTree, ddr_args)
> > > >     ddrtree_res$Z <- t(ddrtree_res$Z)
> > > >     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > > >     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > > >     return(ddrtree_res$Z)
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> > > > Best,
> > > > Ilya
> > > 
> > > 
> > > Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask. Here are my code and error:
> > > > harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> > > > harmony_embedding[seq_len(5), seq_len(5)]
> > > > harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
> > > > Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
> > > > Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
> > > > Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
> > > > Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
> > > > Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> > > > get_ddr <- function(harmony_Z, ndim=2) {
> > > > ncells <- nrow(harmony_Z)
> > > > ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > > > ddr_args <- c(list(
> > > > X = harmony_Z,
> > > > dimensions = ndim, ## LOW DIMENSIONALITY
> > > > ncenter = ncenter,
> > > > verbose = FALSE))
> > > > ddrtree_res <- do.call(DDRTree, ddr_args)
> > > > ddrtree_res$Z <- t(ddrtree_res$Z)
> > > > row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > > > colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > > > return(ddrtree_res$Z)
> > > > }
> > > > get_ddr(harmony_embedding)
> > > > Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
> > > > Error: ncenters must be greater than or equal to ncol(X)
> > > 
> > > 
> > > How can I solve such a problem? Thanks for your answer !
> > 
> > 
> > I meet the same problem. Have you solved it?
> 
> Anyone solved this yet?

this is all because of a stupid mistake in DDRTree() in my point of view:
![image](https://github.com/user-attachments/assets/8d29cabe-bd51-4cb2-b0fd-c3113051074d)
so my solution is to ignore the ncenter parameter, leaving it to be null

**Comment by LeeWang21** [comment]
> > Dear [@yuGithuuub](https://github.com/yuGithuuub),
> > I currently do not have plans to integrate Harmony into the full Monocle framework. In my own analyses, I found that the trajectory inference algorithm used by Monocle, DDRTree, works just as well on a cell-by-gene matrix as a cell-by-PCs matrix. So I use DDRTree directly on my Harmonized PCA matrix to return the trajectory embedding.
> > ```
> > library(DDRTree)
> > get_ddr <- function(harmony_Z, ndim=2) {
> >     ncells <- nrow(harmony_Z)
> >     ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> >     ddr_args <- c(list(
> >         X = harmony_Z, 
> >         dimensions = ndim, ## LOW DIMENSIONALITY
> >         ncenter = ncenter, 
> >         verbose = FALSE))
> >     ddrtree_res <- do.call(DDRTree, ddr_args)
> >     ddrtree_res$Z <- t(ddrtree_res$Z)
> >     row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> >     colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> >     return(ddrtree_res$Z)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the code above, `harmony_Z` is a cell-by-PC matrix of Harmonized cell embeddings and `ndim` is the number of dimensions you want to get from the DDRTree inference. This is not a full trajectory analysis but it can help you to visualize your cells in a "trajectory space."
> > Best,
> > Ilya
> 
> Hello,I have encountered a problem when i run the function of get_ddr,and would like to ask. Here are my code and error:
> 
> > harmony_embedding <- Seurat::Embeddings(seuratObject, 'harmony')
> > harmony_embedding[seq_len(5), seq_len(5)]
> > harmony_1  harmony_2 harmony_3   harmony_4  harmony_5
> > Q9D5_AAACCCAAGCACTAAA-1  1.819167  -7.420685 -6.262630   0.3244117  0.9872209
> > Q9D5_AAACCCAAGCGATCGA-1 -9.997331  13.725940  4.829441 -13.7063330  3.9843493
> > Q9D5_AAACCCACAGTAACAA-1 -4.230632  -9.308852 -3.642947   0.1326170 -1.7054477
> > Q9D5_AAACGAAAGGATTCAA-1 -8.199931 -10.121518 -3.336982   1.8577525 -1.6456189
> > Q9D5_AAACGAAAGTCATAGA-1 -5.126308 -10.118114 -4.421629   0.4208384 -1.4270345
> > get_ddr <- function(harmony_Z, ndim=2) {
> > ncells <- nrow(harmony_Z)
> > ncenter <- round(2 * 100 * log(ncells) / (log(ncells) + log(100)))
> > ddr_args <- c(list(
> > X = harmony_Z,
> > dimensions = ndim, ## LOW DIMENSIONALITY
> > ncenter = ncenter,
> > verbose = FALSE))
> > ddrtree_res <- do.call(DDRTree, ddr_args)
> > ddrtree_res$Z <- t(ddrtree_res$Z)
> > row.names(ddrtree_res$Z) <- row.names(harmony_Z)
> > colnames(ddrtree_res$Z) <- colnames(harmony_Z)
> > return(ddrtree_res$Z)
> > }
> > get_ddr(harmony_embedding)
> > Error in (function (X, dimensions = 2, initial_method = NULL, maxIter = 20,  :
> > Error: ncenters must be greater than or equal to ncol(X)
> 
> How can I solve such a problem? Thanks for your answer !

I met the same problem. After checking the DDRTree package, I found the input matrix for `DDRTree` function should be D x N (PCs x Cells in this case). Moreover, extra steps are required to run the `monocle::orderCells`. Thus, I modified and combined the codes in this issue and monocle package to define a final function: `run_ddrtree_from_harmony`
```r
# Function to decide a good number of centers for running DDRTree on big datasets
cal_ncenter <- function(ncells, ncells_limit = 100) {
    round(2 * ncells_limit * log(ncells) / (log(ncells) + log(ncells_limit)))
}

# Main function to integrate Harmony embedding with monocle2 DDRTree
run_ddrtree_from_harmony <- function(cds, harmony_Z, ndim = 2) {
    #cds: The cds object created in monocle2
    #harmony_Z: (PCs x Cells) The Harmony PC
    ncells <- ncol(harmony_Z)
    ncenter <- cal_ncenter(ncells)

    # Ensure ncenter >= number of PCs
    ncenter <- max(ncenter, nrow(harmony_Z))

    # Run DDRTree on Harmony embedding
    ddrtree_res <- DDRTree(
        X = harmony_Z,
        dimensions = ndim,
        ncenter = ncenter,
        verbose = FALSE
    )

    # Assign names to embedding components
    if (ncol(ddrtree_res$Y) == ncol(cds)) {
        colnames(ddrtree_res$Y) <- colnames(harmony_Z)
    } else {
        colnames(ddrtree_res$Y) <- paste0("Y_", seq_len(ncol(ddrtree_res$Y)))
    }
    colnames(ddrtree_res$Z) <- colnames(harmony_Z)

    # Store embeddings in monocle2 CDS
    cds@reducedDimW <- ddrtree_res$W
    cds@reducedDimS <- ddrtree_res$Z
    cds@reducedDimK <- ddrtree_res$Y
    cds@auxOrderingData[["DDRTree"]]$objective_vals <- ddrtree_res$objective_vals

    # Compute pairwise distances and MST
    adjusted_K <- Matrix::t(reducedDimK(cds))
    dp <- as.matrix(dist(adjusted_K))
    cellPairwiseDistances(cds) <- dp

    graph <- igraph::graph.adjacency(dp, mode = "undirected", weighted = TRUE)
    mst <- igraph::minimum.spanning.tree(graph)
    minSpanningTree(cds) <- mst

    cds@dim_reduce_type <- "DDRTree"

    # Assign root and order cells
    cds <- monocle:::findNearestPointOnMST(cds)

    return(cds)
}
```
Hope these can help everyone

best,
Wang21
