### ISSUE TITLE
reference map

### ISSUE THREAD

**Issue by Winnie09** [immunogenomics/harmony#75]
Hi,

I wonder whether Harmony has a similar function to the Seurat function `FindIntegrationAnchors() `where I can specify a reference study? For example, if I am integrating datasets from study1, study2, and study3, and I want to map study2 and 3 each to study1, then in Seurat I can specify in the parameter `reference = study1`.  Does Harmony have a similar function? Thanks!

**Comment by ilyakorsunsky** [comment]
Dear @Winnie09, 

I am happy to say that we have included this option! Whether you use `HarmonyMatrix` (with a PCA matrix) or `RunHarmony` (with a Seurat or SCE object), just add the parameter `reference_values="study1"`. For example, with a Seurat object, you might run: 

```{r}
obj <- RunHarmony("orig.ident", reference_values="study1")
```

If you want to include several anchors (e.g. if you have some reference cases and controls), you can also specify multiple reference values: 

```{r}
obj <- RunHarmony("orig.ident", reference_values=c("reference_case", "reference_control"))
```

Here, cells from `reference_case` will not be mixed with those from `reference_control` and all other cells will be mapped to these two anchors. 

This is a less often used feature, so please do let me know how goes! 

Best, 
Ilya
