### ISSUE TITLE
Harmony timing out for dataset of 30000 cells

### ISSUE THREAD

**Issue by chintanparekh2301** [immunogenomics/harmony#77]
Hello,

I tried running the following on two machines- a macbookpro with 16GB RAM (4 cores) and a linux server with 16 cores (4 GB per core). The dat file is a matrix with 30000 cells and  PC embeddings for 20 PCs. I used 4 variables for integration from the metadat file. The run for 30,000 cells times out on both machines. A subset of the data (200 cells - named dat2) runs fine on both machines in under a minute. 

```r
library(harmony)

dat = readRDS('/home/rcf-proj3/cp2/mat.RDS')
meta = readRDS('/home/rcf-proj3/cp2/meta.RDS')

dat2 = dat[c(1:100,6000:6100),]
meta2 = meta[c(1:100,6000:6100),]

harmonized_pcs <- HarmonyMatrix(
  data_mat  = dat2,
  meta_data = meta2,
  vars_use  = c('protocol', 'method', "S.Score", "G2M.Score"),
  do_pca    = FALSE
)
saveRDS(harmonized_pcs, '/home/rcf-proj3/cp2/harmonized_pctest.RDS')

harmonized_pcs <- HarmonyMatrix(
  data_mat  = dat,
  meta_data = meta,
  vars_use  = c('protocol', 'method', "S.Score", "G2M.Score"),
  do_pca    = FALSE
)
saveRDS(harmonized_pcs, '/home/rcf-proj3/cp2/harmonized_pc.RDS')
```

Thank you very much

**Comment by ilyakorsunsky** [comment]
Dear @chintanparekh2301, 

Right now, Harmony does not support continuous variables, such as `S.score` and `G2M.Score`. My guess is that Harmony converts these continuous variables into categorical ones and thus creates ~30,000 unique batch values. I will leave this issue open until I include an automated check for this issue. 

Thanks for letting me know about this issue! 

Best, 
Ilya

**Comment by kew24** [comment]
Hi @ilyakorsunsky, thanks for your work on this package! 

I'm not sure that Harmony was ever fixed to include an automated check against regressing on continuous variables, as mentioned in https://github.com/immunogenomics/harmony/issues/77#issuecomment-592595794. I tried using a continuous variable as my `group.by.vars`, and am experiencing it making seemingly *very slow* progress. 

I think adding a descriptive message/warning/error should be fairly easy to implement and will help users understand what's going on / why it's taking so long. Something like "Harmony does not currently support continuous variables in `group.by.vars`. Consider binning your continuous variable into a categorical one and Harmonize over the binned categorical variable. Using a continuous variable may take a long time" (wording pulled from https://github.com/immunogenomics/harmony/issues/117#issuecomment-863401339). If you don't have time or bandwidth, let me know and I'd consider doing it myself and making a PR.
