### ISSUE TITLE
Error installing harmony: lazy loading failed 

### ISSUE THREAD

**Issue by shaln** [immunogenomics/harmony#83]
Hello.

I am having problem installing harmony, and this is the error message I received: 

```
Error: (converted from warning) package 'Rcpp' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'harmony'
* removing 'C:/Program Files/R/R-3.6.2/library/harmony'
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘C:/Users/shaln/AppData/Local/Temp/Rtmp636xdU/file36c237862bc/harmony_1.0.tar.gz’ had non-zero exit status
```

I re-installed the package "Rcpp", hoping it'll fix this problem, but I still had the same error. I previously had this lazy loading error with other packages cause R was trying to install to a network drive and I managed to fix it by having R install all packages to the C drive instead, but this is not working for harmony. 

What should I do to fix this? Thank you.

**Comment by lyuguol** [comment]
> Hello.
> 
> I am having problem installing harmony, and this is the error message I received:
> 
> ```
> Error: (converted from warning) package 'Rcpp' was built under R version 3.6.3
> Execution halted
> ERROR: lazy loading failed for package 'harmony'
> * removing 'C:/Program Files/R/R-3.6.2/library/harmony'
> Error: Failed to install 'harmony' from GitHub:
>   (converted from warning) installation of package ‘C:/Users/shaln/AppData/Local/Temp/Rtmp636xdU/file36c237862bc/harmony_1.0.tar.gz’ had non-zero exit status
> ```
> 
> I re-installed the package "Rcpp", hoping it'll fix this problem, but I still had the same error. I previously had this lazy loading error with other packages cause R was trying to install to a network drive and I managed to fix it by having R install all packages to the C drive instead, but this is not working for harmony.
> 
> What should I do to fix this? Thank you.

Hello shaln,

Did you manage to install harmony on your Mac/Windows?

Thank you, and I look forward to your update.

Best,

Guoliang
