### ISSUE TITLE
Fail to install harmony

### ISSUE THREAD

**Issue by arielyh** [immunogenomics/harmony#85]
Hi,
I'm trying to install harmony through RStudio on Windows 10. I have both Rcpp and RCurl installed. But I got the following error. I've seen similar posts but without a fixation suggestion. Thank you very much.
> library(Rcpp)
Warning message:
package ‘Rcpp’ was built under R version 3.6.3 
> library(devtools)
Loading required package: usethis
Warning messages:
1: package ‘devtools’ was built under R version 3.6.3 
2: package ‘usethis’ was built under R version 3.6.3 
> install_github("immunogenomics/harmony")
Downloading GitHub repo immunogenomics/harmony@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                
2: CRAN packages only                 
3: None                               
4: RCurl (1.98-1.1 -> 1.98-1.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
3
√  checking for file 'C:\Users\AppData\Local\Temp\RtmpwVfv8P\remotes49846efa6f29\immunogenomics-harmony-88b1e2a/DESCRIPTION' ... 
-  preparing 'harmony': (1.9s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'harmony_1.0.tar.gz'
   Warning: file 'harmony/configure' did not have execute permissions: corrected
   
Installing package into ‘C:/Users/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'harmony' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c harmony.cpp -o harmony.o
harmony.cpp: In member function 'void harmony::init_cluster_cpp(unsigned int)':
harmony.cpp:69:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (C > 0 && C < K) {
                  ^
harmony.cpp: In member function 'CUBETYPE harmony::moe_ridge_get_betas_cpp()':
harmony.cpp:236:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (unsigned k = 0; k < K; k++) { 
                          ^
C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o harmony.dll tmp.def RcppExports.o harmony.o -LC:/PROGRA~1/R/R-36~1.0/bin/i386 -lRlapack -LC:/PROGRA~1/R/R-36~1.0/bin/i386 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-36~1.0/bin/i386 -lR
installing to C:/Users/Documents/R/win-library/3.6/00LOCK-harmony/00new/harmony/libs/i386

*** arch - x64
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/Documents/R/win-library/3.6/RcppProgress/include"     "-DUSE_FLOAT_TYPES=0"   -O2 -Wall  -mtune=generic -c harmony.cpp -o harmony.o
harmony.cpp: In member function 'void harmony::init_cluster_cpp(unsigned int)':
harmony.cpp:69:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (C > 0 && C < K) {
                  ^
harmony.cpp: In member function 'CUBETYPE harmony::moe_ridge_get_betas_cpp()':
harmony.cpp:236:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (unsigned k = 0; k < K; k++) { 
                          ^
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o harmony.dll tmp.def RcppExports.o harmony.o -LC:/PROGRA~1/R/R-36~1.0/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-36~1.0/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-36~1.0/bin/x64 -lR
installing to C:/Users/Documents/R/win-library/3.6/00LOCK-harmony/00new/harmony/libs/x64
** R
** data
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'Rcpp' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'harmony'
* removing 'C:/Users/Documents/R/win-library/3.6/harmony'
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘C:/Users/AppData/Local/Temp/RtmpwVfv8P/file4984265a3e09/harmony_1.0.tar.gz’ had non-zero exit status

**Comment by shaln** [comment]
Hello. I recently had this same error and managed to fix it by updating my R to the latest version - a new version came out a week or two ago! Hope this helps.

**Comment by arielyh** [comment]
> Hello. I recently had this same error and managed to fix it by updating my R to the latest version - a new version came out a week or two ago! Hope this helps.

Hi Shaln,
Yes. I updated to R.3.6.3 and deleted the older version. Then installed harmony successfully! Thank you so much!
