### ISSUE TITLE
How to decide the number of PCs to use for Harmony?

### ISSUE THREAD

**Issue by Cumol** [immunogenomics/harmony#89]
In your vignettes, you always use "all" the PCs calculated which is usually 20 PCs (for example in the Seurat 3 vignette).

In the detailed workflow, you use the first two PCs.

How do you decide on the number of PCs to use?

If I go by the usual methods of choosing PCs I would do an elbow plot and take a point where the variance does not increase much more. Would that be a reasonable way to choose the number of PCs?

**Comment by Cumol** [comment]
I settled on using one visualization from your detailed walkthrough that shows the scaled embeddings per PC used.

```
harmonyObj$Z_cos %>% t %>% data.frame() %>% 
    cbind(meta_data) %>% 
    tidyr::gather(key, val, X1:X20) %>% 
    ggplot(aes(reorder(gsub('X', 'PC', key), as.integer(gsub('X', '', key))), val)) + 
        geom_boxplot(aes(color = dataset)) + 
        scale_color_manual(values = colors_use) + 
        labs(x = 'PC number', y = 'PC embedding value', title = 'Z_cos (unit scaled PCA embeddings) for all 20 PCs') + 
        theme_tufte(base_size = 14) + geom_rangeframe() + 
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
        NULL
```

I then picked the number of PCs where there was less variability between the datasets.

Is that the correct approach?

**Comment by ilyakorsunsky** [comment]
Dear @Cumol, 

That sounds like a great approach! I would say that whatever is right for PCA should also be right for Harmony. 

Best, 
Ilya

**Comment by PernilleYR** [comment]
Dear @Cumol  and @ilyakorsunsky 

I found your conversation interesting. Would you mind elaborating why would that make sense and also how did you evaluate the number of PCs where there was less variability between datasets. I am also not sure how to interpret this last part. I applied the same code and it is mainly the 1st 10 PCs that shows variability between datasets (the 1st having the most variability); did you select the X 1st PCs that shows variability or the PCs that had small variability?

Thank you, 

Best, 
Pernille
