### ISSUE TITLE
vars_use in HarmonyMatrix

### ISSUE THREAD

**Issue by micdonato** [immunogenomics/harmony#93]
Hi all,

I am trying to use `HarmonyMatrix` with a data.frame and no matter what I try for `vars_use` I still get an error:

This is my code:

```
normData = CreateSeuratObject(counts = sparsedf,
                             project = "dengue_visc", min.cells = 5) %>%
    Seurat::NormalizeData(verbose = FALSE, normalization.method = "LogNormalize", 
                         scale.factor = 10000) 

normData@meta.data$pstatus = samples$pstatus
normData@meta.data$patient = samples$patient
normData@meta.data$numberDengueReads = samples$numberDengueReads

# found in the Seurat github, how to get the normalized data from a seurat object
normDataMatrix = as.matrix(normData@assays$RNA@data)

testobj = HarmonyMatrix(normDataMatrix, meta_data = normData@meta.data, vars_use = 'stim')

```

and the error is:

```
Error in HarmonyMatrix(normDataMatrix, meta_data = normData@meta.data,  : 
  must provide variables names (e.g. vars_use=‘stim’)
```

No matter what I use in `vars_use` I get the error. The vignette says: `If meta_data is dataframe, this defined which variable(s) to remove (character vector).`

So I tried:
1. empty character vector
2. a gene name (the first one in the matrix)
3. `'stim'`

But no success.

What am I doing wrong? I must use the normalized matrix and get the corrected gene expression for my project, but at this point I am not sure it is possible.

**Comment by pati-ni** [comment]
Apologies for the 3 year delay as issues were not monitored rigorously. Not sure if you managed to resolve this. Please update to the latest version of the software.

It looks like the `stim` column is not present in the metadata. replacing it with `pstatus` or `patient`
